exports.UFRUU_AGENT = [
    { username : 'ufruu3g04', master: 'ufruu3g'},

]
exports.UFRUU_AGENT_1 = [
    { username: 'ufruu0101', master: 'ufruu01' },
    { username: 'ufruu035', master: 'ufruu03' },
    { username: 'ufruu0405', master: 'ufruu04' },
    { username: 'ufruu0407', master: 'ufruu04' },
    { username: 'ufruu040j', master: 'ufruu04' },
    { username: 'ufruu040p', master: 'ufruu04' },
    { username: 'ufruu0413', master: 'ufruu04' },
    { username: 'ufruu047', master: 'ufruu04' },
    { username: 'ufruu0501', master: 'ufruu05' },
    { username: 'ufruu0502', master: 'ufruu05' },
    { username: 'ufruu0504', master: 'ufruu05' },
    { username: 'ufruu0509', master: 'ufruu05' },
    { username: 'ufruu0511', master: 'ufruu05' },
    { username: 'ufruu0603', master: 'ufruu06' },
    { username: 'ufruu0607', master: 'ufruu06' },
    { username: 'ufruu0608', master: 'ufruu06' },
    { username: 'ufruu060h', master: 'ufruu06' },
    { username: 'ufruu060l', master: 'ufruu06' },
    { username: 'ufruu060v', master: 'ufruu06' },
    { username: 'ufruu061', master: 'ufruu06' },
    { username: 'ufruu0612', master: 'ufruu06' },
    { username: 'ufruu0615', master: 'ufruu06' },
    { username: 'ufruu0617', master: 'ufruu06' },
    { username: 'ufruu061a', master: 'ufruu06' },
    { username: 'ufruu062', master: 'ufruu06' },
    { username: 'ufruu0621', master: 'ufruu06' },
    { username: 'ufruu0622', master: 'ufruu06' },
    { username: 'ufruu063', master: 'ufruu06' },
    { username: 'ufruu0630', master: 'ufruu06' },
    { username: 'ufruu0638', master: 'ufruu06' },
    { username: 'ufruu064', master: 'ufruu06' },
    { username: 'ufruu0641', master: 'ufruu06' },
    { username: 'ufruu0646', master: 'ufruu06' },
    { username: 'ufruu0649', master: 'ufruu06' },
    { username: 'ufruu0652', master: 'ufruu06' },
    { username: 'ufruu066', master: 'ufruu06' },
    { username: 'ufruu068', master: 'ufruu06' },
    { username: 'ufruu0902', master: 'ufruu09' },
    { username: 'ufruu0904', master: 'ufruu09' },
    { username: 'ufruu0909', master: 'ufruu09' },
    { username: 'ufruu090b', master: 'ufruu09' },
    { username: 'ufruu090j', master: 'ufruu09' },
    { username: 'ufruu090r', master: 'ufruu09' },
    { username: 'ufruu090x', master: 'ufruu09' },
    { username: 'ufruu0910', master: 'ufruu09' },
    { username: 'ufruu091h', master: 'ufruu09' },
    { username: 'ufruu091i', master: 'ufruu09' },
    { username: 'ufruu091l', master: 'ufruu09' },
    { username: 'ufruu091m', master: 'ufruu09' },
    { username: 'ufruu0923', master: 'ufruu09' },
    { username: 'ufruu0926', master: 'ufruu09' },
    { username: 'ufruu0927', master: 'ufruu09' },
    { username: 'ufruu0928', master: 'ufruu09' },
    { username: 'ufruu0930', master: 'ufruu09' },
    { username: 'ufruu0940', master: 'ufruu09' },
    { username: 'ufruu0941', master: 'ufruu09' },
    { username: 'ufruu0953', master: 'ufruu09' },
    { username: 'ufruu0958', master: 'ufruu09' },
    { username: 'ufruu0977', master: 'ufruu09' },
    { username: 'ufruu0a09', master: 'ufruu0a' },
    { username: 'ufruu0a11', master: 'ufruu0a' },
    { username: 'ufruu0a14', master: 'ufruu0a' },
    { username: 'ufruu0a21', master: 'ufruu0a' },
    { username: 'ufruu0b01', master: 'ufruu0b' },
    { username: 'ufruu0b02', master: 'ufruu0b' },
    { username: 'ufruu0c01', master: 'ufruu0c' },
    { username: 'ufruu0c02', master: 'ufruu0c' },
    { username: 'ufruu0c03', master: 'ufruu0c' },
    { username: 'ufruu0c06', master: 'ufruu0c' },
    { username: 'ufruu0c08', master: 'ufruu0c' },
    { username: 'ufruu0c09', master: 'ufruu0c' },
    { username: 'ufruu0c13', master: 'ufruu0c' },
    { username: 'ufruu0c16', master: 'ufruu0c' },
    { username: 'ufruu0c18', master: 'ufruu0c' },
    { username: 'ufruu0c19', master: 'ufruu0c' },
    { username: 'ufruu0d05', master: 'ufruu0d' },
    { username: 'ufruu0d12', master: 'ufruu0d' },
    { username: 'ufruu0g06', master: 'ufruu0g' },
    { username: 'ufruu0g08', master: 'ufruu0g' },
    { username: 'ufruu0g16', master: 'ufruu0g' },
    { username: 'ufruu0g19', master: 'ufruu0g' },
    { username: 'ufruu0h00', master: 'ufruu0h' },
    { username: 'ufruu0h02', master: 'ufruu0h' },
    { username: 'ufruu0h04', master: 'ufruu0h' },
    { username: 'ufruu0h05', master: 'ufruu0h' },
    { username: 'ufruu0h06', master: 'ufruu0h' },
    { username: 'ufruu0i01', master: 'ufruu0i' },
    { username: 'ufruu0i02', master: 'ufruu0i' },
    { username: 'ufruu0i03', master: 'ufruu0i' },
    { username: 'ufruu0i06', master: 'ufruu0i' },
    { username: 'ufruu0i0a', master: 'ufruu0i' },
    { username: 'ufruu0i0b', master: 'ufruu0i' },
    { username: 'ufruu0i0c', master: 'ufruu0i' },
    { username: 'ufruu0i0f', master: 'ufruu0i' },
    { username: 'ufruu0i11', master: 'ufruu0i' },
    { username: 'ufruu0i12', master: 'ufruu0i' },
    { username: 'ufruu0i19', master: 'ufruu0i' },
    { username: 'ufruu0i23', master: 'ufruu0i' },
    { username: 'ufruu0i24', master: 'ufruu0i' },
    { username: 'ufruu0i28', master: 'ufruu0i' },
    { username: 'ufruu0i35', master: 'ufruu0i' },
    { username: 'ufruu0i37', master: 'ufruu0i' },
    { username: 'ufruu0i38', master: 'ufruu0i' },
    { username: 'ufruu0j00', master: 'ufruu0j' },
    { username: 'ufruu0j01', master: 'ufruu0j' },
    { username: 'ufruu0j02', master: 'ufruu0j' },
    { username: 'ufruu0j04', master: 'ufruu0j' },
    { username: 'ufruu0j09', master: 'ufruu0j' },
    { username: 'ufruu0j10', master: 'ufruu0j' },
    { username: 'ufruu0l03', master: 'ufruu0l' },
    { username: 'ufruu0m00', master: 'ufruu0m' },
    { username: 'ufruu0m03', master: 'ufruu0m' },
    { username: 'ufruu0m06', master: 'ufruu0m' },
    { username: 'ufruu0m08', master: 'ufruu0m' },
    { username: 'ufruu0m10', master: 'ufruu0m' },
    { username: 'ufruu0m12', master: 'ufruu0m' },
    { username: 'ufruu0m17', master: 'ufruu0m' },
    { username: 'ufruu0m22', master: 'ufruu0m' },
    { username: 'ufruu0m23', master: 'ufruu0m' },
    { username: 'ufruu0m26', master: 'ufruu0m' },
    { username: 'ufruu0m28', master: 'ufruu0m' },
    { username: 'ufruu0m40', master: 'ufruu0m' },
    { username: 'ufruu0m51', master: 'ufruu0m' },
    { username: 'ufruu0n01', master: 'ufruu0n' },
    { username: 'ufruu0n03', master: 'ufruu0n' },
    { username: 'ufruu0n06', master: 'ufruu0n' },
    { username: 'ufruu0n07', master: 'ufruu0n' },
    { username: 'ufruu0n09', master: 'ufruu0n' },
    { username: 'ufruu0n11', master: 'ufruu0n' },
    { username: 'ufruu0n13', master: 'ufruu0n' },
    { username: 'ufruu0p02', master: 'ufruu0p' },
    { username: 'ufruu0p04', master: 'ufruu0p' },
    { username: 'ufruu0p07', master: 'ufruu0p' },
    { username: 'ufruu0p12', master: 'ufruu0p' },
    { username: 'ufruu0p13', master: 'ufruu0p' },
    { username: 'ufruu0p22', master: 'ufruu0p' },
    { username: 'ufruu0p27', master: 'ufruu0p' },
    { username: 'ufruu0p29', master: 'ufruu0p' },
    { username: 'ufruu0p31', master: 'ufruu0p' },
    { username: 'ufruu0p46', master: 'ufruu0p' },
    { username: 'ufruu0p57', master: 'ufruu0p' },
    { username: 'ufruu0p58', master: 'ufruu0p' },
    { username: 'ufruu0p68', master: 'ufruu0p' },
    { username: 'ufruu0p71', master: 'ufruu0p' },
    { username: 'ufruu0p77', master: 'ufruu0p' },
    { username: 'ufruu0p78', master: 'ufruu0p' },
    { username: 'ufruu0p80', master: 'ufruu0p' },
    { username: 'ufruu0q00', master: 'ufruu0q' },
    { username: 'ufruu0q01', master: 'ufruu0q' },
    { username: 'ufruu0q04', master: 'ufruu0q' },
    { username: 'ufruu0q13', master: 'ufruu0q' },
    { username: 'ufruu0q15', master: 'ufruu0q' },
    { username: 'ufruu0q16', master: 'ufruu0q' },
    { username: 'ufruu0q19', master: 'ufruu0q' },
    { username: 'ufruu0r05', master: 'ufruu0r' },
    { username: 'ufruu0r09', master: 'ufruu0r' },
    { username: 'ufruu0s00', master: 'ufruu0s' },
    { username: 'ufruu0s01', master: 'ufruu0s' },
    { username: 'ufruu0s02', master: 'ufruu0s' },
    { username: 'ufruu0s03', master: 'ufruu0s' },
    { username: 'ufruu0s05', master: 'ufruu0s' },
    { username: 'ufruu0s06', master: 'ufruu0s' },
    { username: 'ufruu0s08', master: 'ufruu0s' },
    { username: 'ufruu0t01', master: 'ufruu0t' },
    { username: 'ufruu0t04', master: 'ufruu0t' },
    { username: 'ufruu0t06', master: 'ufruu0t' },
    { username: 'ufruu0t10', master: 'ufruu0t' },
    { username: 'ufruu0t31', master: 'ufruu0t' },
    { username: 'ufruu0t32', master: 'ufruu0t' },
    { username: 'ufruu0t37', master: 'ufruu0t' },
    { username: 'ufruu0t40', master: 'ufruu0t' },
    { username: 'ufruu0t44', master: 'ufruu0t' },
    { username: 'ufruu0t53', master: 'ufruu0t' },
    { username: 'ufruu0t54', master: 'ufruu0t' },
    { username: 'ufruu0x00', master: 'ufruu0x' },
    { username: 'ufruu0x01', master: 'ufruu0x' },
    { username: 'ufruu0x02', master: 'ufruu0x' },
    { username: 'ufruu0x03', master: 'ufruu0x' },
    { username: 'ufruu0x05', master: 'ufruu0x' },
    { username: 'ufruu0x06', master: 'ufruu0x' },
    { username: 'ufruu0x09', master: 'ufruu0x' },
    { username: 'ufruu0x0a', master: 'ufruu0x' },
    { username: 'ufruu0x0c', master: 'ufruu0x' },
    { username: 'ufruu0x0d', master: 'ufruu0x' },
    { username: 'ufruu0x13', master: 'ufruu0x' },
    { username: 'ufruu0x16', master: 'ufruu0x' },
    { username: 'ufruu0x18', master: 'ufruu0x' },
    { username: 'ufruu0x19', master: 'ufruu0x' },
    { username: 'ufruu0x20', master: 'ufruu0x' },
    { username: 'ufruu0x21', master: 'ufruu0x' },
    { username: 'ufruu0x23', master: 'ufruu0x' },
    { username: 'ufruu0x25', master: 'ufruu0x' },
    { username: 'ufruu0x26', master: 'ufruu0x' },
    { username: 'ufruu0x27', master: 'ufruu0x' },
    { username: 'ufruu0x28', master: 'ufruu0x' },
    { username: 'ufruu0x29', master: 'ufruu0x' },
    { username: 'ufruu0x30', master: 'ufruu0x' },
    { username: 'ufruu0x32', master: 'ufruu0x' },
    { username: 'ufruu0x33', master: 'ufruu0x' },
    { username: 'ufruu0x35', master: 'ufruu0x' },
    { username: 'ufruu0x36', master: 'ufruu0x' },
    { username: 'ufruu0x40', master: 'ufruu0x' },
    { username: 'ufruu0x42', master: 'ufruu0x' },
    { username: 'ufruu0x44', master: 'ufruu0x' },
    { username: 'ufruu0x45', master: 'ufruu0x' },
    { username: 'ufruu0x46', master: 'ufruu0x' },
    { username: 'ufruu0x47', master: 'ufruu0x' },
    { username: 'ufruu0x48', master: 'ufruu0x' },
    { username: 'ufruu0x50', master: 'ufruu0x' },
    { username: 'ufruu0x53', master: 'ufruu0x' },
    { username: 'ufruu0x54', master: 'ufruu0x' },
    { username: 'ufruu0x55', master: 'ufruu0x' },
    { username: 'ufruu1001', master: 'ufruu10' },
    { username: 'ufruu1101', master: 'ufruu11' },
    { username: 'ufruu1402', master: 'ufruu14' },
    { username: 'ufruu1405', master: 'ufruu14' },
    { username: 'ufruu1406', master: 'ufruu14' },
    { username: 'ufruu1407', master: 'ufruu14' },
    { username: 'ufruu1501', master: 'ufruu15' },
    { username: 'ufruu1502', master: 'ufruu15' },
    { username: 'ufruu1504', master: 'ufruu15' },
    { username: 'ufruu1505', master: 'ufruu15' },
    { username: 'ufruu1507', master: 'ufruu15' },
    { username: 'ufruu1510', master: 'ufruu15' },
    { username: 'ufruu1513', master: 'ufruu15' },
    { username: 'ufruu1514', master: 'ufruu15' },
    { username: 'ufruu1601', master: 'ufruu16' },
    { username: 'ufruu1603', master: 'ufruu16' },
    { username: 'ufruu1609', master: 'ufruu16' },
    { username: 'ufruu1802', master: 'ufruu18' },
    { username: 'ufruu1803', master: 'ufruu18' },
    { username: 'ufruu1904', master: 'ufruu19' },
    { username: 'ufruu1905', master: 'ufruu19' },
    { username: 'ufruu1906', master: 'ufruu19' },
    { username: 'ufruu1a01', master: 'ufruu1a' },
    { username: 'ufruu1a02', master: 'ufruu1a' },
    { username: 'ufruu1c02', master: 'ufruu1c' },
    { username: 'ufruu1c03', master: 'ufruu1c' },
    { username: 'ufruu1d01', master: 'ufruu1d' },
    { username: 'ufruu1d04', master: 'ufruu1d' },
    { username: 'ufruu1d05', master: 'ufruu1d' },
    { username: 'ufruu1d06', master: 'ufruu1d' },
    { username: 'ufruu1d07', master: 'ufruu1d' },
    { username: 'ufruu1d08', master: 'ufruu1d' },
    { username: 'ufruu1d0a', master: 'ufruu1d' },
    { username: 'ufruu1d12', master: 'ufruu1d' },
    { username: 'ufruu1d13', master: 'ufruu1d' },
    { username: 'ufruu1d17', master: 'ufruu1d' },
    { username: 'ufruu1d18', master: 'ufruu1d' },
    { username: 'ufruu1d19', master: 'ufruu1d' },
    { username: 'ufruu1d1d', master: 'ufruu1d' },
    { username: 'ufruu1d25', master: 'ufruu1d' },
    { username: 'ufruu1d27', master: 'ufruu1d' },
    { username: 'ufruu1d29', master: 'ufruu1d' },
    { username: 'ufruu1e02', master: 'ufruu1e' },
    { username: 'ufruu1e04', master: 'ufruu1e' },
    { username: 'ufruu1h01', master: 'ufruu1h' },
    { username: 'ufruu1h06', master: 'ufruu1h' },
    { username: 'ufruu1h07', master: 'ufruu1h' },
    { username: 'ufruu1h09', master: 'ufruu1h' },
    { username: 'ufruu1h11', master: 'ufruu1h' },
    { username: 'ufruu1i01', master: 'ufruu1i' },
    { username: 'ufruu1j02', master: 'ufruu1j' },
    { username: 'ufruu1l05', master: 'ufruu1l' },
    { username: 'ufruu1m01', master: 'ufruu1m' },
    { username: 'ufruu1m10', master: 'ufruu1m' },
    { username: 'ufruu1m13', master: 'ufruu1m' },
    { username: 'ufruu1m14', master: 'ufruu1m' },
    { username: 'ufruu1m15', master: 'ufruu1m' },
    { username: 'ufruu1m18', master: 'ufruu1m' },
    { username: 'ufruu1m19', master: 'ufruu1m' },
    { username: 'ufruu1m20', master: 'ufruu1m' },
    { username: 'ufruu1m21', master: 'ufruu1m' },
    { username: 'ufruu1n01', master: 'ufruu1n' },
    { username: 'ufruu1n02', master: 'ufruu1n' },
    { username: 'ufruu1o01', master: 'ufruu1o' },
    { username: 'ufruu1o04', master: 'ufruu1o' },
    { username: 'ufruu1t08', master: 'ufruu1t' },
    { username: 'ufruu1t10', master: 'ufruu1t' },
    { username: 'ufruu1t11', master: 'ufruu1t' },
    { username: 'ufruu1t15', master: 'ufruu1t' },
    { username: 'ufruu1u01', master: 'ufruu1u' },
    { username: 'ufruu1u04', master: 'ufruu1u' },
    { username: 'ufruu1w01', master: 'ufruu1w' },
    { username: 'ufruu1w02', master: 'ufruu1w' },
    { username: 'ufruu1w04', master: 'ufruu1w' },
    { username: 'ufruu1w05', master: 'ufruu1w' },
    { username: 'ufruu1w08', master: 'ufruu1w' },
    { username: 'ufruu1w10', master: 'ufruu1w' },
    { username: 'ufruu1y02', master: 'ufruu1y' },
    { username: 'ufruu1y04', master: 'ufruu1y' },
    { username: 'ufruu1y07', master: 'ufruu1y' },
    { username: 'ufruu1y12', master: 'ufruu1y' },
    { username: 'ufruu1y13', master: 'ufruu1y' },
    { username: 'ufruu2001', master: 'ufruu20' },
    { username: 'ufruu2002', master: 'ufruu20' },
    { username: 'ufruu2005', master: 'ufruu20' },
    { username: 'ufruu2009', master: 'ufruu20' },
    { username: 'ufruu2012', master: 'ufruu20' },
    { username: 'ufruu2101', master: 'ufruu21' },
    { username: 'ufruu2102', master: 'ufruu21' },
    { username: 'ufruu2103', master: 'ufruu21' },
    { username: 'ufruu2307', master: 'ufruu23' },
    { username: 'ufruu2604', master: 'ufruu26' },
    { username: 'ufruu2606', master: 'ufruu26' },
    { username: 'ufruu2803', master: 'ufruu28' },
    { username: 'ufruu2805', master: 'ufruu28' },
    { username: 'ufruu2806', master: 'ufruu28' },
    { username: 'ufruu2a08', master: 'ufruu2a' },
    { username: 'ufruu2b02', master: 'ufruu2b' },
    { username: 'ufruu2b03', master: 'ufruu2b' },
    { username: 'ufruu2b05', master: 'ufruu2b' },
    { username: 'ufruu2c02', master: 'ufruu2c' },
    { username: 'ufruu2c03', master: 'ufruu2c' },
    { username: 'ufruu2c04', master: 'ufruu2c' },
    { username: 'ufruu2c05', master: 'ufruu2c' },
    { username: 'ufruu2c07', master: 'ufruu2c' },
    { username: 'ufruu2c08', master: 'ufruu2c' },
    { username: 'ufruu2c10', master: 'ufruu2c' },
    { username: 'ufruu2c12', master: 'ufruu2c' },
    { username: 'ufruu2d01', master: 'ufruu2d' },
    { username: 'ufruu2d05', master: 'ufruu2d' },
    { username: 'ufruu2d06', master: 'ufruu2d' },
    { username: 'ufruu2d12', master: 'ufruu2d' },
    { username: 'ufruu2d16', master: 'ufruu2d' },
    { username: 'ufruu2d18', master: 'ufruu2d' },
    { username: 'ufruu2d27', master: 'ufruu2d' },
    { username: 'ufruu2f14', master: 'ufruu2f' },
    { username: 'ufruu2f22', master: 'ufruu2f' },
    { username: 'ufruu2f25', master: 'ufruu2f' },
    { username: 'ufruu2h01', master: 'ufruu2h' },
    { username: 'ufruu2h02', master: 'ufruu2h' },
    { username: 'ufruu2h03', master: 'ufruu2h' },
    { username: 'ufruu2i06', master: 'ufruu2i' },
    { username: 'ufruu2k01', master: 'ufruu2k' },
    { username: 'ufruu2k09', master: 'ufruu2k' },
    { username: 'ufruu2k10', master: 'ufruu2k' },
    { username: 'ufruu2k11', master: 'ufruu2k' },
    { username: 'ufruu2k13', master: 'ufruu2k' },
    { username: 'ufruu2k24', master: 'ufruu2k' },
    { username: 'ufruu2m03', master: 'ufruu2m' },
    { username: 'ufruu2n03', master: 'ufruu2n' },
    { username: 'ufruu2n06', master: 'ufruu2n' },
    { username: 'ufruu2n12', master: 'ufruu2n' },
    { username: 'ufruu2n15', master: 'ufruu2n' },
    { username: 'ufruu2n22', master: 'ufruu2n' },
    { username: 'ufruu2n47', master: 'ufruu2n' },
    { username: 'ufruu2n53', master: 'ufruu2n' },
    { username: 'ufruu2n59', master: 'ufruu2n' },
    { username: 'ufruu2n81', master: 'ufruu2n' },
    { username: 'ufruu2n86', master: 'ufruu2n' },
    { username: 'ufruu2n92', master: 'ufruu2n' },
    { username: 'ufruu2p07', master: 'ufruu2p' },
    { username: 'ufruu2r03', master: 'ufruu2r' },
    { username: 'ufruu2s07', master: 'ufruu2s' },
    { username: 'ufruu2s09', master: 'ufruu2s' },
    { username: 'ufruu2t01', master: 'ufruu2t' },
    { username: 'ufruu2t06', master: 'ufruu2t' },
    { username: 'ufruu2t09', master: 'ufruu2t' },
    { username: 'ufruu2t10', master: 'ufruu2t' },
    { username: 'ufruu2t11', master: 'ufruu2t' },
    { username: 'ufruu2v04', master: 'ufruu2v' },
    { username: 'ufruu2x01', master: 'ufruu2x' },
    { username: 'ufruu2x07', master: 'ufruu2x' },
    { username: 'ufruu2x13', master: 'ufruu2x' },
    { username: 'ufruu2x16', master: 'ufruu2x' },
    { username: 'ufruu2y01', master: 'ufruu2y' },
    { username: 'ufruu2y02', master: 'ufruu2y' },
    { username: 'ufruu2y06', master: 'ufruu2y' },
    { username: 'ufruu2y13', master: 'ufruu2y' },
    { username: 'ufruu2y16', master: 'ufruu2y' },
    { username: 'ufruu2y19', master: 'ufruu2y' },
    { username: 'ufruu2y20', master: 'ufruu2y' },
    { username: 'ufruu2y21', master: 'ufruu2y' },
    { username: 'ufruu2y22', master: 'ufruu2y' },
    { username: 'ufruu2y24', master: 'ufruu2y' },
    { username: 'ufruu2y26', master: 'ufruu2y' },
    { username: 'ufruu2y28', master: 'ufruu2y' },
    { username: 'ufruu2y29', master: 'ufruu2y' },
    { username: 'ufruu2y30', master: 'ufruu2y' },
    { username: 'ufruu2y31', master: 'ufruu2y' },
    { username: 'ufruu2y32', master: 'ufruu2y' },
    { username: 'ufruu2y33', master: 'ufruu2y' },
    { username: 'ufruu2y35', master: 'ufruu2y' },
    { username: 'ufruu2y36', master: 'ufruu2y' },
    { username: 'ufruu2z04', master: 'ufruu2z' },
    { username: 'ufruu2z09', master: 'ufruu2z' },
    { username: 'ufruu2z11', master: 'ufruu2z' },
    { username: 'ufruu2z15', master: 'ufruu2z' },
    { username: 'ufruu2z18', master: 'ufruu2z' },
    { username: 'ufruu2z20', master: 'ufruu2z' },
    { username: 'ufruu2z21', master: 'ufruu2z' },
    { username: 'ufruu2z32', master: 'ufruu2z' },
    { username: 'ufruu2z34', master: 'ufruu2z' },
    { username: 'ufruu2z35', master: 'ufruu2z' },
    { username: 'ufruu2z41', master: 'ufruu2z' },
    { username: 'ufruu2z42', master: 'ufruu2z' },
    { username: 'ufruu2z46', master: 'ufruu2z' },
    { username: 'ufruu2z47', master: 'ufruu2z' },
    { username: 'ufruu2z49', master: 'ufruu2z' },
    { username: 'ufruu2z52', master: 'ufruu2z' },
    { username: 'ufruu2z60', master: 'ufruu2z' },
    { username: 'ufruu2z62', master: 'ufruu2z' },
    { username: 'ufruu2z65', master: 'ufruu2z' },
    { username: 'ufruu2z71', master: 'ufruu2z' },
    { username: 'ufruu2z73', master: 'ufruu2z' },
    { username: 'ufruu2z75', master: 'ufruu2z' },
    { username: 'ufruu2z76', master: 'ufruu2z' },
    { username: 'ufruu3101', master: 'ufruu31' },
    { username: 'ufruu3102', master: 'ufruu31' },
    { username: 'ufruu3103', master: 'ufruu31' },
    { username: 'ufruu3104', master: 'ufruu31' },
    { username: 'ufruu3105', master: 'ufruu31' },
    { username: 'ufruu3107', master: 'ufruu31' },
    { username: 'ufruu3201', master: 'ufruu32' },
    { username: 'ufruu3202', master: 'ufruu32' },
    { username: 'ufruu3203', master: 'ufruu32' },
    { username: 'ufruu3204', master: 'ufruu32' },
    { username: 'ufruu3205', master: 'ufruu32' },
    { username: 'ufruu3206', master: 'ufruu32' },
    { username : 'ufruu2k08', master: 'ufruu2k'},
    { username : 'ufruu2n27', master: 'ufruu2n'},
    { username : 'ufruu2n29', master: 'ufruu2n'},
    { username : 'ufruu2n37', master: 'ufruu2n'},
    { username : 'ufruu2n39', master: 'ufruu2n'},
    { username : 'ufruu2p11', master: 'ufruu2p'},
    { username : 'ufruu2p12', master: 'ufruu2p'},
    { username : 'ufruu2s08', master: 'ufruu2s'},
    { username : 'ufruu2z16', master: 'ufruu2z'},
    { username : 'ufruu3509', master: 'ufruu35'},
    { username : 'ufruu3514', master: 'ufruu35'},
    { username : 'ufruu4712', master: 'ufruu47'},
    { username : 'ufruu4803', master: 'ufruu48'},
    { username : 'ufruu4811', master: 'ufruu48'},
    { username : 'ufruu5201', master: 'ufruu52'},
    { username : 'ufruu5202', master: 'ufruu52'},
    { username : 'ufruu5403', master: 'ufruu54'},
    { username : 'ufruu5404', master: 'ufruu54'},
    { username : 'ufruu6673', master: 'ufruu66'},
    { username : 'ufruu6682', master: 'ufruu66'},
    { username : 'ufruu9f06', master: 'ufruu9f'},
    { username : 'ufruu9f10', master: 'ufruu9f'},
    { username : 'ufruu0p26', master: 'ufruu0p'},
    { username : 'ufruu3333', master: 'ufruu33'},
    { username : 'ufruu0m42', master: 'ufruu0m'},
    { username : 'ufruu0m43', master: 'ufruu0m'},
    { username : 'ufruu0m45', master: 'ufruu0m'},
    { username : 'ufruu6503', master: 'ufruu65'},
    { username : 'ufruu6504', master: 'ufruu65'},
    { username : 'ufruu6683', master: 'ufruu66'},
    { username : 'ufruv0110', master: 'ufruv01'},
    { username : 'ufruu0c21', master: 'ufruu0c'},
    { username : 'ufruu0m47', master: 'ufruu0m'},
    { username : 'ufruu0m48', master: 'ufruu0m'},
    { username : 'ufruu0p63', master: 'ufruu0p'},
    { username : 'ufruu0p64', master: 'ufruu0p'},
    { username : 'ufruu2d15', master: 'ufruu2d'},
    { username : 'ufruu2k12', master: 'ufruu2k'},
    { username : 'ufruu2n43', master: 'ufruu2n'},
    { username : 'ufruu2r04', master: 'ufruu2r'},
    { username : 'ufruu2y14', master: 'ufruu2y'},
    { username : 'ufruu2z12', master: 'ufruu2z'},
    { username : 'ufruu2z22', master: 'ufruu2z'},
    { username : 'ufruu2z25', master: 'ufruu2z'},
    { username : 'ufruu3602', master: 'ufruu36'},
    { username : 'ufruu4003', master: 'ufruu40'},
    { username : 'ufruu4405', master: 'ufruu44'},
    { username : 'ufruu4713', master: 'ufruu47'},
    { username : 'ufruu4828', master: 'ufruu48'},
    { username : 'ufruu4831', master: 'ufruu48'},
    { username : 'ufruu4835', master: 'ufruu48'},
    { username : 'ufruu5203', master: 'ufruu52'},
    { username : 'ufruu5402', master: 'ufruu54'},
    { username : 'ufruu5405', master: 'ufruu54'},
    { username : 'ufruu5802', master: 'ufruu58'},
    { username : 'ufruu5803', master: 'ufruu58'},
    { username : 'ufruu8822', master: 'ufruu88'},
    { username : 'ufruu9935', master: 'ufruu99'},
    { username : 'ufruu5101', master: 'ufruu51'},
    { username : 'ufruu2008', master: 'ufruu20'},
    { username : 'ufruu2i04', master: 'ufruu2i'},
]
exports.UFRUU_AGENT_2 = [
    // { username : 'ufruu5806', master: 'ufruu58'},
    // { username : 'ufruu6101', master: 'ufruu61'},
    // { username : 'ufruu6103', master: 'ufruu61'},
    // { username : 'ufruu6201', master: 'ufruu62'},
    // { username : 'ufruu6202', master: 'ufruu62'},
    // { username : 'ufruu6205', master: 'ufruu62'},
    // { username : 'ufruu6206', master: 'ufruu62'},
    // { username : 'ufruu6209', master: 'ufruu62'},
    // { username : 'ufruu6210', master: 'ufruu62'},
    // { username : 'ufruu6211', master: 'ufruu62'},
    // { username : 'ufruu6213', master: 'ufruu62'},
    // { username : 'ufruu6402', master: 'ufruu64'},
    // { username : 'ufruu6521', master: 'ufruu65'},
    // { username : 'ufruu6601', master: 'ufruu66'},
    // { username : 'ufruu6602', master: 'ufruu66'},
    // { username : 'ufruu6603', master: 'ufruu66'},
    // { username : 'ufruu6606', master: 'ufruu66'},
    // { username : 'ufruu6608', master: 'ufruu66'},
    // { username : 'ufruu6610', master: 'ufruu66'},
    // { username : 'ufruu6612', master: 'ufruu66'},
    // { username : 'ufruu6614', master: 'ufruu66'},
    // { username : 'ufruu6615', master: 'ufruu66'},
    // { username : 'ufruu6617', master: 'ufruu66'},
    // { username : 'ufruu6618', master: 'ufruu66'},
    // { username : 'ufruu6619', master: 'ufruu66'},
    // { username : 'ufruu6623', master: 'ufruu66'},
    // { username : 'ufruu6624', master: 'ufruu66'},
    // { username : 'ufruu6628', master: 'ufruu66'},
    // { username : 'ufruu6633', master: 'ufruu66'},
    // { username : 'ufruu6636', master: 'ufruu66'},
    // { username : 'ufruu6668', master: 'ufruu66'},
    // { username : 'ufruu6669', master: 'ufruu66'},
    // { username : 'ufruu6674', master: 'ufruu66'},
    // { username : 'ufruu6677', master: 'ufruu66'},
    // { username : 'ufruu6680', master: 'ufruu66'},
    // { username : 'ufruu6681', master: 'ufruu66'},
    // { username : 'ufruu6684', master: 'ufruu66'},
    // { username : 'ufruu6692', master: 'ufruu66'},
    // { username : 'ufruu7104', master: 'ufruu71'},
    // { username : 'ufruu7201', master: 'ufruu72'},
    // { username : 'ufruu7202', master: 'ufruu72'},
    // { username : 'ufruu7203', master: 'ufruu72'},
    // { username : 'ufruu7305', master: 'ufruu73'},
    // { username : 'ufruu7306', master: 'ufruu73'},
    // { username : 'ufruu7324', master: 'ufruu73'},
    // { username : 'ufruu7327', master: 'ufruu73'},
    // { username : 'ufruu7403', master: 'ufruu74'},
    // { username : 'ufruu7501', master: 'ufruu75'},
    // { username : 'ufruu7602', master: 'ufruu76'},
    // { username : 'ufruu7604', master: 'ufruu76'},
    // { username : 'ufruu7605', master: 'ufruu76'},
    // { username : 'ufruu7701', master: 'ufruu77'},
    // { username : 'ufruu7901', master: 'ufruu79'},
    // { username : 'ufruu8802', master: 'ufruu88'},
    // { username : 'ufruu8804', master: 'ufruu88'},
    // { username : 'ufruu8805', master: 'ufruu88'},
    // { username : 'ufruu8806', master: 'ufruu88'},
    // { username : 'ufruu8808', master: 'ufruu88'},
    // { username : 'ufruu8811', master: 'ufruu88'},
    // { username : 'ufruu8815', master: 'ufruu88'},
    // { username : 'ufruu8818', master: 'ufruu88'},
    // { username : 'ufruu8819', master: 'ufruu88'},
    // { username : 'ufruu8820', master: 'ufruu88'},
    // { username : 'ufruu8826', master: 'ufruu88'},
    // { username : 'ufruu8828', master: 'ufruu88'},
    // { username : 'ufruu8829', master: 'ufruu88'},
    // { username : 'ufruu8832', master: 'ufruu88'},
    // { username : 'ufruu8833', master: 'ufruu88'},
    // { username : 'ufruu8834', master: 'ufruu88'},
    // { username : 'ufruu8835', master: 'ufruu88'},
    // { username : 'ufruu8836', master: 'ufruu88'},
    // { username : 'ufruu8837', master: 'ufruu88'},
    // { username : 'ufruu9701', master: 'ufruu97'},
    // { username : 'ufruu9702', master: 'ufruu97'},
    // { username : 'ufruu9703', master: 'ufruu97'},
    // { username : 'ufruu9901', master: 'ufruu99'},
    // { username : 'ufruu9902', master: 'ufruu99'},
    // { username : 'ufruu9907', master: 'ufruu99'},
    // { username : 'ufruu9908', master: 'ufruu99'},
    // { username : 'ufruu9909', master: 'ufruu99'},
    // { username : 'ufruu990c', master: 'ufruu99'},
    // { username : 'ufruu990e', master: 'ufruu99'},
    // { username : 'ufruu9913', master: 'ufruu99'},
    // { username : 'ufruu9914', master: 'ufruu99'},
    // { username : 'ufruu9915', master: 'ufruu99'},
    // { username : 'ufruu9919', master: 'ufruu99'},
    // { username : 'ufruu9924', master: 'ufruu99'},
    // { username : 'ufruu9925', master: 'ufruu99'},
    // { username : 'ufruu9928', master: 'ufruu99'},
    // { username : 'ufruu9932', master: 'ufruu99'},
    // { username : 'ufruu9941', master: 'ufruu99'},
    // { username : 'ufruu9942', master: 'ufruu99'},
    // { username : 'ufruu9947', master: 'ufruu99'},
    // { username : 'ufruu9948', master: 'ufruu99'},
    // { username : 'ufruu9950', master: 'ufruu99'},
    // { username : 'ufruu9952', master: 'ufruu99'},
    // { username : 'ufruu9953', master: 'ufruu99'},
    // { username : 'ufruu9954', master: 'ufruu99'},
    // { username : 'ufruu9955', master: 'ufruu99'},
    // { username : 'ufruu9957', master: 'ufruu99'},
    // { username : 'ufruu9f04', master: 'ufruu9f'},
    // { username : 'ufruu9f08', master: 'ufruu9f'},
    // { username : 'ufruu9f17', master: 'ufruu9f'},
    // { username : 'ufruu9f18', master: 'ufruu9f'},
    // { username : 'ufruu9f19', master: 'ufruu9f'},
    // { username : 'ufruu9j02', master: 'ufruu9j'},
    // { username : 'ufruu9j03', master: 'ufruu9j'},
    // { username : 'ufruuk801', master: 'ufruuk8'},
    // { username : 'ufruuk805', master: 'ufruuk8'},
    // { username : 'ufruuk807', master: 'ufruuk8'},
    // { username : 'ufruuk812', master: 'ufruuk8'},
    // { username : 'ufruuk817', master: 'ufruuk8'},
    // { username : 'ufruuk819', master: 'ufruuk8'},
    // { username : 'ufruuk825', master: 'ufruuk8'},
    // { username : 'ufruuk835', master: 'ufruuk8'},
    // { username : 'ufruuk840', master: 'ufruuk8'},
    // { username : 'ufruuk844', master: 'ufruuk8'},
    // { username : 'ufruuk845', master: 'ufruuk8'},
    // { username : 'ufruuk847', master: 'ufruuk8'},
    // { username : 'ufruuk848', master: 'ufruuk8'},
    // { username : 'ufruuk849', master: 'ufruuk8'},
    // { username : 'ufruuli01', master: 'ufruuli'},
    // { username : 'ufruup168', master: 'ufruup1'},
    // { username : 'ufruuq102', master: 'ufruuq1'},
    // { username : 'ufruut901', master: 'ufruut9'},
    // { username : 'ufruut912', master: 'ufruut9'},
    // { username : 'ufruut917', master: 'ufruut9'},
    // { username : 'ufruut919', master: 'ufruut9'},
    // { username : 'ufruut925', master: 'ufruut9'},
    // { username : 'ufruut934', master: 'ufruut9'},
    // { username : 'ufruut938', master: 'ufruut9'},
    // { username : 'ufruut940', master: 'ufruut9'},
    // { username : 'ufruut953', master: 'ufruut9'},
    // { username : 'ufruut955', master: 'ufruut9'},
    // { username : 'ufruut964', master: 'ufruut9'},
    // { username : 'ufruutd01', master: 'ufruutd'},
    // { username : 'ufruu0t59', master: 'ufruu0t'},
    // { username : 'ufruu1w11', master: 'ufruu1w'},
    // { username : 'ufruu2b06', master: 'ufruu2b'},
    // { username : 'ufruu3h06', master: 'ufruu3h'},
    // { username : 'ufruu3k28', master: 'ufruu3k'},
    // { username : 'ufruu4898', master: 'ufruu48'},
    // { username : 'ufruu7335', master: 'ufruu73'},
    // { username : 'ufruu7904', master: 'ufruu79'},
    // { username : 'ufruu9958', master: 'ufruu99'},
    // { username : 'ufruut965', master: 'ufruut9'},
    // { username : 'ufruu1w09', master: 'ufruu1w'},
    // { username : 'ufruu3335', master: 'ufruu33'},
    // { username : 'ufruu3e34', master: 'ufruu3e'},
    // { username : 'ufruu3f30', master: 'ufruu3f'},
    // { username : 'ufruu3k26', master: 'ufruu3k'},
    // { username : 'ufruu7334', master: 'ufruu73'},
    // { username : 'ufruu7903', master: 'ufruu79'},
    // { username : 'ufruv0308', master: 'ufruv03'},
    // { username : 'ufruu3k27', master: 'ufruu3k'},
    // { username : 'ufruu2d28', master: 'ufruu2d'},
    // { username : 'ufruu5308', master: 'ufruu53'},
    // { username : 'ufruu2z08', master: 'ufruu2z'},
    // { username : 'ufruu2z27', master: 'ufruu2z'},
    // { username : 'ufruu2z70', master: 'ufruu2z'},
    // { username : 'ufruu2z74', master: 'ufruu2z'},
    // { username : 'ufruu3e29', master: 'ufruu3e'},
    // { username : 'ufruu3j06', master: 'ufruu3j'},
    // { username : 'ufruu3k24', master: 'ufruu3k'},
    // { username : 'ufruu4a01', master: 'ufruu4a'},
    // { username : 'ufruu4a02', master: 'ufruu4a'},
    // { username : 'ufruu4b02', master: 'ufruu4b'},
    // { username : 'ufruu4d03', master: 'ufruu4d'},
    // { username : 'ufruu4e01', master: 'ufruu4e'},
    // { username : 'ufruu4e03', master: 'ufruu4e'},
    // { username : 'ufruu4e07', master: 'ufruu4e'},
    // { username : 'ufruu7301', master: 'ufruu73'},
    // { username : 'ufruut961', master: 'ufruut9'},
    // { username : 'ufruv0506', master: 'ufruv05'},
    // { username : 'ufruu0313', master: 'ufruu03'},
    // { username : 'ufruu0l04', master: 'ufruu0l'},
    // { username : 'ufruu0m55', master: 'ufruu0m'},
    // { username : 'ufruu0p76', master: 'ufruu0p'},
    // { username : 'ufruu0p79', master: 'ufruu0p'},
    // { username : 'ufruu0s09', master: 'ufruu0s'},
    // { username : 'ufruu0t42', master: 'ufruu0t'},
    // { username : 'ufruu0t43', master: 'ufruu0t'},
    // { username : 'ufruu0t45', master: 'ufruu0t'},
    // { username : 'ufruu0t47', master: 'ufruu0t'},
    // { username : 'ufruu0t48', master: 'ufruu0t'},
    // { username : 'ufruu0t49', master: 'ufruu0t'},
    // { username : 'ufruu0t50', master: 'ufruu0t'},
    // { username : 'ufruu0t52', master: 'ufruu0t'},
    // { username : 'ufruu1515', master: 'ufruu15'},
    // { username : 'ufruu2b04', master: 'ufruu2b'},
    // { username : 'ufruu2d25', master: 'ufruu2d'},
    // { username : 'ufruu2f02', master: 'ufruu2f'},
    // { username : 'ufruu2n89', master: 'ufruu2n'},
    // { username : 'ufruu2n90', master: 'ufruu2n'},
    // { username : 'ufruu2n93', master: 'ufruu2n'},
    // { username : 'ufruu2n94', master: 'ufruu2n'},
    // { username : 'ufruu2n95', master: 'ufruu2n'},
    // { username : 'ufruu3921', master: 'ufruu39'},
    // { username : 'ufruu3e18', master: 'ufruu3e'},
    // { username : 'ufruu3e19', master: 'ufruu3e'},
    // { username : 'ufruu3e21', master: 'ufruu3e'},
    // { username : 'ufruu3e23', master: 'ufruu3e'},
    // { username : 'ufruu3e25', master: 'ufruu3e'},
    // { username : 'ufruu3e26', master: 'ufruu3e'},
    // { username : 'ufruu3f27', master: 'ufruu3f'},
    // { username : 'ufruu3k17', master: 'ufruu3k'},
    // { username : 'ufruu3k18', master: 'ufruu3k'},
    // { username : 'ufruu3k19', master: 'ufruu3k'},
    // { username : 'ufruu3k20', master: 'ufruu3k'},
    // { username : 'ufruu3k21', master: 'ufruu3k'},
    // { username : 'ufruu3k22', master: 'ufruu3k'},
    // { username : 'ufruu3n01', master: 'ufruu3n'},
    // { username : 'ufruu3z02', master: 'ufruu3z'},
    // { username : 'ufruu4102', master: 'ufruu41'},
    // { username : 'ufruu4894', master: 'ufruu48'},
    // { username : 'ufruu5532', master: 'ufruu55'},
    // { username : 'ufruu7326', master: 'ufruu73'},
    // { username : 'ufruu7329', master: 'ufruu73'},
    // { username : 'ufruu7330', master: 'ufruu73'},
    // { username : 'ufruu7331', master: 'ufruu73'},
    // { username : 'ufruu8825', master: 'ufruu88'},
    // { username : 'ufruuk832', master: 'ufruuk8'},
    // { username : 'ufruuk833', master: 'ufruuk8'},
    // { username : 'ufruuk836', master: 'ufruuk8'},
    // { username : 'ufruuk837', master: 'ufruuk8'},
    // { username : 'ufruuk838', master: 'ufruuk8'},
    // { username : 'ufruuk839', master: 'ufruuk8'},
    // { username : 'ufruut947', master: 'ufruut9'},
    // { username : 'ufruut948', master: 'ufruut9'},
    // { username : 'ufruut949', master: 'ufruut9'},
    // { username : 'ufruut950', master: 'ufruut9'},
    // { username : 'ufruut952', master: 'ufruut9'},
    // { username : 'ufruut954', master: 'ufruut9'},
    // { username : 'ufruv0104', master: 'ufruv01'},
    // { username : 'ufruv0303', master: 'ufruv03'},
    // { username : 'ufruv0304', master: 'ufruv03'},
    // { username : 'ufruv0307', master: 'ufruv03'},
    // { username : 'ufruu4893', master: 'ufruu48'},
    // { username : 'ufruuli02', master: 'ufruuli'},
    // { username : 'ufruut957', master: 'ufruut9'},
    // { username : 'ufruut958', master: 'ufruut9'},
    // { username : 'ufruut959', master: 'ufruut9'},
    // { username : 'ufruut960', master: 'ufruut9'},
    // { username : 'ufruv0305', master: 'ufruv03'},
    // { username : 'ufruu0m53', master: 'ufruu0m'},
    // { username : 'ufruu0m54', master: 'ufruu0m'},
    // { username : 'ufruu0p74', master: 'ufruu0p'},
    // { username : 'ufruu0p75', master: 'ufruu0p'},
    // { username : 'ufruu0t41', master: 'ufruu0t'},
    // { username : 'ufruu0t46', master: 'ufruu0t'},
    // { username : 'ufruu0t51', master: 'ufruu0t'},
    // { username : 'ufruu1h10', master: 'ufruu1h'},
    // { username : 'ufruu1u09', master: 'ufruu1u'},
    // { username : 'ufruu2d24', master: 'ufruu2d'},
    // { username : 'ufruu2d26', master: 'ufruu2d'},
    // { username : 'ufruu2n91', master: 'ufruu2n'},
    // { username : 'ufruu2z66', master: 'ufruu2z'},
    // { username : 'ufruu2z67', master: 'ufruu2z'},
    // { username : 'ufruu2z68', master: 'ufruu2z'},
    // { username : 'ufruu3e20', master: 'ufruu3e'},
    // { username : 'ufruu3e22', master: 'ufruu3e'},
    // { username : 'ufruu3j12', master: 'ufruu3j'},
    // { username : 'ufruu3k01', master: 'ufruu3k'},
    // { username : 'ufruu3l01', master: 'ufruu3l'},
    // { username : 'ufruu3n02', master: 'ufruu3n'},
    // { username : 'ufruu3z03', master: 'ufruu3z'},
    // { username : 'ufruu4892', master: 'ufruu48'},
    // { username : 'ufruu7325', master: 'ufruu73'},
    // { username : 'ufruu7702', master: 'ufruu77'},
    // { username : 'ufruuk834', master: 'ufruuk8'},
    // { username : 'ufruu0a22', master: 'ufruu0a'},
    // { username : 'ufruu0p16', master: 'ufruu0p'},
    // { username : 'ufruu0p70', master: 'ufruu0p'},
    // { username : 'ufruu0p72', master: 'ufruu0p'},
    // { username : 'ufruu0p73', master: 'ufruu0p'},
    // { username : 'ufruu0t28', master: 'ufruu0t'},
    // { username : 'ufruu0t38', master: 'ufruu0t'},
    // { username : 'ufruu0t39', master: 'ufruu0t'},
    // { username : 'ufruu0x51', master: 'ufruu0x'},
    // { username : 'ufruu0x52', master: 'ufruu0x'},
    // { username : 'ufruu1909', master: 'ufruu19'},
    // { username : 'ufruu2004', master: 'ufruu20'},
    // { username : 'ufruu2c11', master: 'ufruu2c'},
    // { username : 'ufruu2d21', master: 'ufruu2d'},
    // { username : 'ufruu2d22', master: 'ufruu2d'},
    // { username : 'ufruu2f26', master: 'ufruu2f'},
    // { username : 'ufruu2f27', master: 'ufruu2f'},
    // { username : 'ufruu2n16', master: 'ufruu2n'},
    // { username : 'ufruu2n82', master: 'ufruu2n'},
    // { username : 'ufruu2n84', master: 'ufruu2n'},
    // { username : 'ufruu2n85', master: 'ufruu2n'},
    // { username : 'ufruu2n87', master: 'ufruu2n'},
    // { username : 'ufruu2n88', master: 'ufruu2n'},
    // { username : 'ufruu2t07', master: 'ufruu2t'},
    // { username : 'ufruu2v03', master: 'ufruu2v'},
    // { username : 'ufruu2z63', master: 'ufruu2z'},
    // { username : 'ufruu2z64', master: 'ufruu2z'},
    // { username : 'ufruu3320', master: 'ufruu33'},
    // { username : 'ufruu3334', master: 'ufruu33'},
    // { username : 'ufruu3426', master: 'ufruu34'},
    // { username : 'ufruu3427', master: 'ufruu34'},
    // { username : 'ufruu3428', master: 'ufruu34'},
    // { username : 'ufruu3c05', master: 'ufruu3c'},
    // { username : 'ufruu3f26', master: 'ufruu3f'},
    // { username : 'ufruu3g05', master: 'ufruu3g'},
    // { username : 'ufruu3h05', master: 'ufruu3h'},
    // { username : 'ufruu3j11', master: 'ufruu3j'},
    // { username : 'ufruu3s05', master: 'ufruu3s'},
    // { username : 'ufruu3s06', master: 'ufruu3s'},
    // { username : 'ufruu3s07', master: 'ufruu3s'},
    // { username : 'ufruu3y03', master: 'ufruu3y'},
    // { username : 'ufruu3z01', master: 'ufruu3z'},
    // { username : 'ufruu5003', master: 'ufruu50'},
    // { username : 'ufruu5418', master: 'ufruu54'},
    // { username : 'ufruu5530', master: 'ufruu55'},
    // { username : 'ufruu6522', master: 'ufruu65'},
    // { username : 'ufruu6523', master: 'ufruu65'},
    // { username : 'ufruu7402', master: 'ufruu74'},
    // { username : 'ufruu7502', master: 'ufruu75'},
    // { username : 'ufruu9f07', master: 'ufruu9f'},
    // { username : 'ufruuk823', master: 'ufruuk8'},
    // { username : 'ufruuk824', master: 'ufruuk8'},
    // { username : 'ufruuk826', master: 'ufruuk8'},
    // { username : 'ufruuk827', master: 'ufruuk8'},
    // { username : 'ufruuk828', master: 'ufruuk8'},
    // { username : 'ufruuk829', master: 'ufruuk8'},
    // { username : 'ufruuk830', master: 'ufruuk8'},
    // { username : 'ufruuk831', master: 'ufruuk8'},
    // { username : 'ufruut907', master: 'ufruut9'},
    // { username : 'ufruut941', master: 'ufruut9'},
    // { username : 'ufruut942', master: 'ufruut9'},
    // { username : 'ufruut943', master: 'ufruut9'},
    // { username : 'ufruut944', master: 'ufruut9'},
    // { username : 'ufruut945', master: 'ufruut9'},
    // { username : 'ufruut946', master: 'ufruut9'},
    // { username : 'ufruu0303', master: 'ufruu03'},
    // { username : 'ufruu0513', master: 'ufruu05'},
    // { username : 'ufruu0g23', master: 'ufruu0g'},
    // { username : 'ufruu0m52', master: 'ufruu0m'},
    // { username : 'ufruu0p69', master: 'ufruu0p'},
    // { username : 'ufruu0t35', master: 'ufruu0t'},
    // { username : 'ufruu0t36', master: 'ufruu0t'},
    // { username : 'ufruu0x43', master: 'ufruu0x'},
    // { username : 'ufruu0x49', master: 'ufruu0x'},
    // { username : 'ufruu1s01', master: 'ufruu1s'},
    // { username : 'ufruu1u06', master: 'ufruu1u'},
    // { username : 'ufruu1u07', master: 'ufruu1u'},
    // { username : 'ufruu1u08', master: 'ufruu1u'},
    // { username : 'ufruu2809', master: 'ufruu28'},
    // { username : 'ufruu2d19', master: 'ufruu2d'},
    // { username : 'ufruu2d20', master: 'ufruu2d'},
    // { username : 'ufruu2n78', master: 'ufruu2n'},
    // { username : 'ufruu2n79', master: 'ufruu2n'},
    // { username : 'ufruu2n80', master: 'ufruu2n'},
    // { username : 'ufruu2z53', master: 'ufruu2z'},
    // { username : 'ufruu2z58', master: 'ufruu2z'},
    // { username : 'ufruu2z59', master: 'ufruu2z'},
    // { username : 'ufruu3425', master: 'ufruu34'},
    // { username : 'ufruu3e16', master: 'ufruu3e'},
    // { username : 'ufruu3f24', master: 'ufruu3f'},
    // { username : 'ufruu3k15', master: 'ufruu3k'},
    // { username : 'ufruu3p04', master: 'ufruu3p'},
    // { username : 'ufruu3p06', master: 'ufruu3p'},
    // { username : 'ufruu3v02', master: 'ufruu3v'},
    // { username : 'ufruu3y02', master: 'ufruu3y'},
    // { username : 'ufruu4857', master: 'ufruu48'},
    // { username : 'ufruu4883', master: 'ufruu48'},
    // { username : 'ufruu4884', master: 'ufruu48'},
    // { username : 'ufruu5306', master: 'ufruu53'},
    // { username : 'ufruu5307', master: 'ufruu53'},
    // { username : 'ufruu7315', master: 'ufruu73'},
    // { username : 'ufruu7316', master: 'ufruu73'},
    // { username : 'ufruu7317', master: 'ufruu73'},
    // { username : 'ufruu7318', master: 'ufruu73'},
    // { username : 'ufruu7319', master: 'ufruu73'},
    // { username : 'ufruu7320', master: 'ufruu73'},
    // { username : 'ufruu7321', master: 'ufruu73'},
    // { username : 'ufruu7322', master: 'ufruu73'},
    // { username : 'ufruu7323', master: 'ufruu73'},
    // { username : 'ufruu7401', master: 'ufruu74'},
    // { username : 'ufruuk813', master: 'ufruuk8'},
    // { username : 'ufruuk816', master: 'ufruuk8'},
    // { username : 'ufruuk818', master: 'ufruuk8'},
    // { username : 'ufruuk820', master: 'ufruuk8'},
    // { username : 'ufruuk821', master: 'ufruuk8'},
    // { username : 'ufruuk822', master: 'ufruuk8'},
    // { username : 'ufruuq104', master: 'ufruuq1'},
    // { username : 'ufruut909', master: 'ufruut9'},
    // { username : 'ufruut915', master: 'ufruut9'},
    // { username : 'ufruut923', master: 'ufruut9'},
    // { username : 'ufruut924', master: 'ufruut9'},
    // { username : 'ufruut926', master: 'ufruut9'},
    // { username : 'ufruut927', master: 'ufruut9'},
    // { username : 'ufruut928', master: 'ufruut9'},
    // { username : 'ufruut929', master: 'ufruut9'},
    // { username : 'ufruut931', master: 'ufruut9'},
    // { username : 'ufruut932', master: 'ufruut9'},
    // { username : 'ufruut933', master: 'ufruut9'},
    // { username : 'ufruut935', master: 'ufruut9'},
    // { username : 'ufruut936', master: 'ufruut9'},
    // { username : 'ufruut937', master: 'ufruut9'},
    // { username : 'ufruut939', master: 'ufruut9'},
    // { username : 'ufruu0c23', master: 'ufruu0c'},
    // { username : 'ufruu0p67', master: 'ufruu0p'},
    // { username : 'ufruu2k25', master: 'ufruu2k'},
    // { username : 'ufruu2n70', master: 'ufruu2n'},
    // { username : 'ufruu2t08', master: 'ufruu2t'},
    // { username : 'ufruu2y25', master: 'ufruu2y'},
    // { username : 'ufruu2z55', master: 'ufruu2z'},
    // { username : 'ufruu2z56', master: 'ufruu2z'},
    // { username : 'ufruu3419', master: 'ufruu34'},
    // { username : 'ufruu3f19', master: 'ufruu3f'},
    // { username : 'ufruu3f21', master: 'ufruu3f'},
    // { username : 'ufruu3f23', master: 'ufruu3f'},
    // { username : 'ufruu3h04', master: 'ufruu3h'},
    // { username : 'ufruu3k11', master: 'ufruu3k'},
    // { username : 'ufruu3k14', master: 'ufruu3k'},
    // { username : 'ufruu5528', master: 'ufruu55'},
    // { username : 'ufruu6403', master: 'ufruu64'},
    // { username : 'ufruu6505', master: 'ufruu65'},
    // { username : 'ufruu6695', master: 'ufruu66'},
    // { username : 'ufruu7303', master: 'ufruu73'},
    // { username : 'ufruu7310', master: 'ufruu73'},
    // { username : 'ufruu7311', master: 'ufruu73'},
    // { username : 'ufruu7312', master: 'ufruu73'},
    // { username : 'ufruuk802', master: 'ufruuk8'},
    // { username : 'ufruuk811', master: 'ufruuk8'},
    // { username : 'ufruuk815', master: 'ufruuk8'},
    // { username : 'ufruuq101', master: 'ufruuq1'},
    // { username : 'ufruut904', master: 'ufruut9'},
    // { username : 'ufruut905', master: 'ufruut9'},
    // { username : 'ufruut911', master: 'ufruut9'},
    // { username : 'ufruut914', master: 'ufruut9'},
    // { username : 'ufruut918', master: 'ufruut9'},
    // { username : 'ufruu0p66', master: 'ufruu0p'},
    // { username : 'ufruu2h04', master: 'ufruu2h'},
    // { username : 'ufruu2z50', master: 'ufruu2z'},
    // { username : 'ufruu3313', master: 'ufruu33'},
    // { username : 'ufruu3517', master: 'ufruu35'},
    // { username : 'ufruu3d07', master: 'ufruu3d'},
    // { username : 'ufruu3e15', master: 'ufruu3e'},
    // { username : 'ufruu3f12', master: 'ufruu3f'},
    // { username : 'ufruu3f15', master: 'ufruu3f'},
    // { username : 'ufruu3h02', master: 'ufruu3h'},
    // { username : 'ufruu3j08', master: 'ufruu3j'},
    // { username : 'ufruu4004', master: 'ufruu40'},
    // { username : 'ufruu4207', master: 'ufruu42'},
    // { username : 'ufruu5209', master: 'ufruu52'},
    // { username : 'ufruu5210', master: 'ufruu52'},
    // { username : 'ufruu5211', master: 'ufruu52'},
    // { username : 'ufruu5212', master: 'ufruu52'},
    // { username : 'ufruu6515', master: 'ufruu65'},
    // { username : 'ufruu6517', master: 'ufruu65'},
    // { username : 'ufruu7302', master: 'ufruu73'},
    // { username : 'ufruu9j04', master: 'ufruu9j'},
    // { username : 'ufruu0g22', master: 'ufruu0g'},
    // { username : 'ufruu0m46', master: 'ufruu0m'},
    // { username : 'ufruu0x39', master: 'ufruu0x'},
    // { username : 'ufruu2z36', master: 'ufruu2z'},
    // { username : 'ufruu2z44', master: 'ufruu2z'},
    // { username : 'ufruu2z45', master: 'ufruu2z'},
    // { username : 'ufruu3a06', master: 'ufruu3a'},
    // { username : 'ufruu3d03', master: 'ufruu3d'},
    // { username : 'ufruu3d06', master: 'ufruu3d'},
    // { username : 'ufruu3h03', master: 'ufruu3h'},
    // { username : 'ufruu3j04', master: 'ufruu3j'},
    // { username : 'ufruu3j05', master: 'ufruu3j'},
    // { username : 'ufruu4864', master: 'ufruu48'},
    // { username : 'ufruu4874', master: 'ufruu48'},
    // { username : 'ufruu5206', master: 'ufruu52'},
    // { username : 'ufruu5207', master: 'ufruu52'},
    // { username : 'ufruu5208', master: 'ufruu52'},
    // { username : 'ufruu7101', master: 'ufruu71'},
    // { username : 'ufruu7102', master: 'ufruu71'},
    // { username : 'ufruu7204', master: 'ufruu72'},
    // { username : 'ufruu7601', master: 'ufruu76'},
    // { username : 'ufruu0p65', master: 'ufruu0p'},
    // { username : 'ufruu0q18', master: 'ufruu0q'},
    // { username : 'ufruu0r08', master: 'ufruu0r'},
    // { username : 'ufruu0x38', master: 'ufruu0x'},
    // { username : 'ufruu2k04', master: 'ufruu2k'},
    // { username : 'ufruu2k19', master: 'ufruu2k'},
    // { username : 'ufruu2k20', master: 'ufruu2k'},
    // { username : 'ufruu2n49', master: 'ufruu2n'},
    // { username : 'ufruu2n56', master: 'ufruu2n'},
    // { username : 'ufruu2n58', master: 'ufruu2n'},
    { username : 'ufruu2s11', master: 'ufruu2s'},
    { username : 'ufruu2y18', master: 'ufruu2y'},
    { username : 'ufruu2z38', master: 'ufruu2z'},
    { username : 'ufruu3212', master: 'ufruu32'},
    { username : 'ufruu3505', master: 'ufruu35'},
    { username : 'ufruu3a04', master: 'ufruu3a'},
    { username : 'ufruu3d04', master: 'ufruu3d'},
    { username : 'ufruu3e10', master: 'ufruu3e'},
    { username : 'ufruu3e11', master: 'ufruu3e'},
    { username : 'ufruu3f02', master: 'ufruu3f'},
    { username : 'ufruu4853', master: 'ufruu48'},
    { username : 'ufruu5205', master: 'ufruu52'},
    { username : 'ufruu6501', master: 'ufruu65'},
    { username : 'ufruu6514', master: 'ufruu65'},
    { username : 'ufruu7103', master: 'ufruu71'},
    { username : 'ufruv0111', master: 'ufruv01'},
    { username : 'ufruu0r07', master: 'ufruu0r'},
    { username : 'ufruu1u05', master: 'ufruu1u'},
    { username : 'ufruu2f04', master: 'ufruu2f'},
    { username : 'ufruu2k15', master: 'ufruu2k'},
    { username : 'ufruu2k16', master: 'ufruu2k'},
    { username : 'ufruu2k17', master: 'ufruu2k'},
    { username : 'ufruu2k18', master: 'ufruu2k'},
    { username : 'ufruu3508', master: 'ufruu35'},
    { username : 'ufruu3c01', master: 'ufruu3c'},
    { username : 'ufruu3c02', master: 'ufruu3c'},
    { username : 'ufruu3d01', master: 'ufruu3d'},
    { username : 'ufruu3e01', master: 'ufruu3e'},
    { username : 'ufruu3e05', master: 'ufruu3e'},
    { username : 'ufruu3e06', master: 'ufruu3e'},
    { username : 'ufruu4406', master: 'ufruu44'},
    { username : 'ufruu4851', master: 'ufruu48'},
    { username : 'ufruu4858', master: 'ufruu48'},
    { username : 'ufruu5204', master: 'ufruu52'},
    { username : 'ufruu6207', master: 'ufruu62'},
    { username : 'ufruu6513', master: 'ufruu65'},
    { username : 'ufruu8824', master: 'ufruu88'},
    { username : 'ufruu0a16', master: 'ufruu0a'},
    { username : 'ufruu0a18', master: 'ufruu0a'},
    { username : 'ufruu0t26', master: 'ufruu0t'},
    { username : 'ufruu0t27', master: 'ufruu0t'},
    { username : 'ufruu0x37', master: 'ufruu0x'},
    { username : 'ufruu1512', master: 'ufruu15'},
    { username : 'ufruu2n48', master: 'ufruu2n'},
    { username : 'ufruu2s10', master: 'ufruu2s'},
    { username : 'ufruu2y12', master: 'ufruu2y'},
    { username : 'ufruu2z28', master: 'ufruu2z'},
    { username : 'ufruu2z29', master: 'ufruu2z'},
    { username : 'ufruu3913', master: 'ufruu39'},
    { username : 'ufruu4830', master: 'ufruu48'},
    { username : 'ufruu5522', master: 'ufruu55'},
    { username : 'ufruu5601', master: 'ufruu56'},
    { username : 'ufruu5804', master: 'ufruu58'},


]
exports.UFRUU_AGENT_3 = [
    // { username : 'ufruu0t18', master: 'ufruu0t'},
    // { username : 'ufruu0t25', master: 'ufruu0t'},
    // { username : 'ufruu2306', master: 'ufruu23'},
    // { username : 'ufruu2k05', master: 'ufruu2k'},
    // { username : 'ufruu2k06', master: 'ufruu2k'},
    // { username : 'ufruu2n31', master: 'ufruu2n'},
    // { username : 'ufruu2p08', master: 'ufruu2p'},
    // { username : 'ufruu2p09', master: 'ufruu2p'},
    // { username : 'ufruu2p10', master: 'ufruu2p'},
    // { username : 'ufruu2s06', master: 'ufruu2s'},
    // { username : 'ufruu2x11', master: 'ufruu2x'},
    // { username : 'ufruu2y03', master: 'ufruu2y'},
    // { username : 'ufruu2y07', master: 'ufruu2y'},
    // { username : 'ufruu2y08', master: 'ufruu2y'},
    // { username : 'ufruu2y09', master: 'ufruu2y'},
    // { username : 'ufruu2y10', master: 'ufruu2y'},
    // { username : 'ufruu2z05', master: 'ufruu2z'},
    // { username : 'ufruu2z06', master: 'ufruu2z'},
    // { username : 'ufruu2z17', master: 'ufruu2z'},
    // { username : 'ufruu3912', master: 'ufruu39'},
    // { username : 'ufruu4303', master: 'ufruu43'},
    // { username : 'ufruu4701', master: 'ufruu47'},
    // { username : 'ufruu4702', master: 'ufruu47'},
    // { username : 'ufruu4704', master: 'ufruu47'},
    // { username : 'ufruu4705', master: 'ufruu47'},
    // { username : 'ufruu4706', master: 'ufruu47'},
    // { username : 'ufruu4707', master: 'ufruu47'},
    // { username : 'ufruu4802', master: 'ufruu48'},
    // { username : 'ufruu4808', master: 'ufruu48'},
    // { username : 'ufruu4812', master: 'ufruu48'},
    // { username : 'ufruu4817', master: 'ufruu48'},
    // { username : 'ufruu4822', master: 'ufruu48'},
    // { username : 'ufruu5001', master: 'ufruu50'},
    // { username : 'ufruu5104', master: 'ufruu51'},
    // { username : 'ufruu5105', master: 'ufruu51'},
    // { username : 'ufruu5514', master: 'ufruu55'},
    // { username : 'ufruu5517', master: 'ufruu55'},
    // { username : 'ufruu5520', master: 'ufruu55'},
    // { username : 'ufruu6634', master: 'ufruu66'},
    // { username : 'ufruu8821', master: 'ufruu88'},
    // { username : 'ufruu8823', master: 'ufruu88'},
    // { username : 'ufruu9940', master: 'ufruu99'},
    // { username : 'ufruu9951', master: 'ufruu99'},
    // { username : 'ufruu9f13', master: 'ufruu9f'},
    // { username : 'ufruu0a15', master: 'ufruu0a'},
    // { username : 'ufruu0d14', master: 'ufruu0d'},
    // { username : 'ufruu0g21', master: 'ufruu0g'},
    // { username : 'ufruu0p62', master: 'ufruu0p'},
    // { username : 'ufruu0r06', master: 'ufruu0r'},
    // { username : 'ufruu0t14', master: 'ufruu0t'},
    // { username : 'ufruu0t19', master: 'ufruu0t'},
    // { username : 'ufruu0t20', master: 'ufruu0t'},
    // { username : 'ufruu0t22', master: 'ufruu0t'},
    // { username : 'ufruu0t24', master: 'ufruu0t'},
    // { username : 'ufruu2605', master: 'ufruu26'},
    // { username : 'ufruu2n18', master: 'ufruu2n'},
    // { username : 'ufruu2n23', master: 'ufruu2n'},
    // { username : 'ufruu2n24', master: 'ufruu2n'},
    // { username : 'ufruu2n26', master: 'ufruu2n'},
    // { username : 'ufruu2s05', master: 'ufruu2s'},
    // { username : 'ufruu2t02', master: 'ufruu2t'},
    // { username : 'ufruu2t03', master: 'ufruu2t'},
    // { username : 'ufruu2x04', master: 'ufruu2x'},
    // { username : 'ufruu2x05', master: 'ufruu2x'},
    // { username : 'ufruu2x06', master: 'ufruu2x'},
    // { username : 'ufruu2x09', master: 'ufruu2x'},
    // { username : 'ufruu2y04', master: 'ufruu2y'},
    // { username : 'ufruu2y05', master: 'ufruu2y'},
    // { username : 'ufruu2z07', master: 'ufruu2z'},
    // { username : 'ufruu3511', master: 'ufruu35'},
    // { username : 'ufruu8814', master: 'ufruu88'},
    // { username : 'ufruu9f11', master: 'ufruu9f'},
    // { username : 'ufruv0201', master: 'ufruv02'},
    // { username : 'ufruu0634', master: 'ufruu06'},
    // { username : 'ufruu0c17', master: 'ufruu0c'},
    // { username : 'ufruu0h09', master: 'ufruu0h'},
    // { username : 'ufruu0p59', master: 'ufruu0p'},
    // { username : 'ufruu0t13', master: 'ufruu0t'},
    // { username : 'ufruu0x34', master: 'ufruu0x'},
    // { username : 'ufruu0z02', master: 'ufruu0z'},
    // { username : 'ufruu2n08', master: 'ufruu2n'},
    // { username : 'ufruu2n09', master: 'ufruu2n'},
    // { username : 'ufruu2n19', master: 'ufruu2n'},
    // { username : 'ufruu2p02', master: 'ufruu2p'},
    // { username : 'ufruu2r01', master: 'ufruu2r'},
    // { username : 'ufruu2s04', master: 'ufruu2s'},
    // { username : 'ufruu2w01', master: 'ufruu2w'},
    // { username : 'ufruu3404', master: 'ufruu34'},
    // { username : 'ufruu3406', master: 'ufruu34'},
    // { username : 'ufruu8816', master: 'ufruu88'},
    // { username : 'ufruu9944', master: 'ufruu99'},
    // { username : 'ufruu0983', master: 'ufruu09'},
    // { username : 'ufruu0g20', master: 'ufruu0g'},
    // { username : 'ufruu0p52', master: 'ufruu0p'},
    // { username : 'ufruu1o03', master: 'ufruu1o'},
    // { username : 'ufruu2f18', master: 'ufruu2f'},
    // { username : 'ufruu2f24', master: 'ufruu2f'},
    // { username : 'ufruu2l05', master: 'ufruu2l'},
    // { username : 'ufruu2p01', master: 'ufruu2p'},
    // { username : 'ufruu2s01', master: 'ufruu2s'},
    // { username : 'ufruu2s02', master: 'ufruu2s'},
    // { username : 'ufruu3501', master: 'ufruu35'},
    // { username : 'ufruu6676', master: 'ufruu66'},
    // { username : 'ufruu9927', master: 'ufruu99'},
    // { username : 'ufruu9939', master: 'ufruu99'},
    // { username : 'ufruu0a10', master: 'ufruu0a'},
    // { username : 'ufruu0p55', master: 'ufruu0p'},
    // { username : 'ufruu0q05', master: 'ufruu0q'},
    // { username : 'ufruu2c06', master: 'ufruu2c'},
    // { username : 'ufruu2f09', master: 'ufruu2f'},
    // { username : 'ufruu3208', master: 'ufruu32'},
    // { username : 'ufruu3502', master: 'ufruu35'},
    // { username : 'ufruu9933', master: 'ufruu99'},
    // { username : 'ufruu0d13', master: 'ufruu0d'},
    // { username : 'ufruu0h08', master: 'ufruu0h'},
    // { username : 'ufruu0q17', master: 'ufruu0q'},
    // { username : 'ufruu1g03', master: 'ufruu1g'},
    // { username : 'ufruu2f16', master: 'ufruu2f'},
    // { username : 'ufruu2f20', master: 'ufruu2f'},
    // { username : 'ufruu2f21', master: 'ufruu2f'},
    // { username : 'ufruu2n01', master: 'ufruu2n'},
    // { username : 'ufruu5501', master: 'ufruu55'},
    // { username : 'ufruu6671', master: 'ufruu66'},
    // { username : 'ufruu6672', master: 'ufruu66'},
    // { username : 'ufruu8812', master: 'ufruu88'},
    // { username : 'ufruu8813', master: 'ufruu88'},
    // { username : 'ufruu9930', master: 'ufruu99'},
    // { username : 'ufruu9f03', master: 'ufruu9f'},
    // { username : 'ufruu0312', master: 'ufruu03'},
    // { username : 'ufruu0p53', master: 'ufruu0p'},
    // { username : 'ufruu1g01', master: 'ufruu1g'},
    // { username : 'ufruu1y10', master: 'ufruu1y'},
    // { username : 'ufruu2807', master: 'ufruu28'},
    // { username : 'ufruu2e02', master: 'ufruu2e'},
    // { username : 'ufruu2f08', master: 'ufruu2f'},
    // { username : 'ufruu2i02', master: 'ufruu2i'},
    // { username : 'ufruu2i03', master: 'ufruu2i'},
    // { username : 'ufruu2l01', master: 'ufruu2l'},
    // { username : 'ufruu2l02', master: 'ufruu2l'},
    // { username : 'ufruu2m01', master: 'ufruu2m'},
    // { username : 'ufruu3302', master: 'ufruu33'},
    // { username : 'ufruu6670', master: 'ufruu66'},
    // { username : 'ufruu8810', master: 'ufruu88'},
    // { username : 'ufruu9f01', master: 'ufruu9f'},
    // { username : 'ufruu9j01', master: 'ufruu9j'},
    // { username : 'ufruu0t09', master: 'ufruu0t'},
    // { username : 'ufruu2j02', master: 'ufruu2j'},
    // { username : 'ufruu2k02', master: 'ufruu2k'},
    // { username : 'ufruu8803', master: 'ufruu88'},
    // { username : 'ufruu9920', master: 'ufruu99'},
    // { username : 'ufruv0503', master: 'ufruv05'},
    // { username : 'ufruv0504', master: 'ufruv05'},
    // { username : 'ufruu0m38', master: 'ufruu0m'},
    // { username : 'ufruu0m39', master: 'ufruu0m'},
    // { username : 'ufruu0x22', master: 'ufruu0x'},
    // { username : 'ufruu1d28', master: 'ufruu1d'},
    // { username : 'ufruu2d10', master: 'ufruu2d'},
    // { username : 'ufruu2d11', master: 'ufruu2d'},
    // { username : 'ufruu2i01', master: 'ufruu2i'},
    // { username : 'ufruu2j01', master: 'ufruu2j'},
    // { username : 'ufruu6660', master: 'ufruu66'},
    // { username : 'ufruu6664', master: 'ufruu66'},
    // { username : 'ufruu9921', master: 'ufruu99'},
    // { username : 'ufruv0302', master: 'ufruv03'},
    // { username : 'ufruv0501', master: 'ufruv05'},
    // { username : 'ufruv0502', master: 'ufruv05'},
    // { username : 'ufruu0984', master: 'ufruu09'},
    // { username : 'ufruu0d11', master: 'ufruu0d'},
    // { username : 'ufruu0l02', master: 'ufruu0l'},
    // { username : 'ufruu0m33', master: 'ufruu0m'},
    // { username : 'ufruu0m35', master: 'ufruu0m'},
    // { username : 'ufruu0m36', master: 'ufruu0m'},
    // { username : 'ufruu0q06', master: 'ufruu0q'},
    // { username : 'ufruu0q12', master: 'ufruu0q'},
    // { username : 'ufruu0x31', master: 'ufruu0x'},
    // { username : 'ufruu1j05', master: 'ufruu1j'},
    // { username : 'ufruu2a11', master: 'ufruu2a'},
    // { username : 'ufruu2d09', master: 'ufruu2d'},
    // { username : 'ufruu2e01', master: 'ufruu2e'},
    // { username : 'ufruu3003', master: 'ufruu30'},
    // { username : 'ufruu3004', master: 'ufruu30'},
    // { username : 'ufruu6645', master: 'ufruu66'},
    // { username : 'ufruu1d26', master: 'ufruu1d'},
    // { username : 'ufruu1l04', master: 'ufruu1l'},
    // { username : 'ufruu2203', master: 'ufruu22'},
    // { username : 'ufruu2d03', master: 'ufruu2d'},
    // { username : 'ufruu6613', master: 'ufruu66'},
    // { username : 'ufruu6638', master: 'ufruu66'},
    // { username : 'ufruu6640', master: 'ufruu66'},
    // { username : 'ufruu6644', master: 'ufruu66'},
    // { username : 'ufruu0m34', master: 'ufruu0m'},
    // { username : 'ufruu0i32', master: 'ufruu0i'},
    // { username : 'ufruu6632', master: 'ufruu66'},
    // { username : 'ufruu2801', master: 'ufruu28'},
    // { username : 'ufruu0d10', master: 'ufruu0d'},
    // { username : 'ufruu2603', master: 'ufruu26'},
    // { username : 'ufruu0981', master: 'ufruu09'},
    // { username : 'ufruu2303', master: 'ufruu23'},
    // { username : 'ufruu0656', master: 'ufruu06'},
    // { username : 'ufruu0m31', master: 'ufruu0m'},
    // { username : 'ufruu0p43', master: 'ufruu0p'},
    // { username : 'ufruu1f10', master: 'ufruu1f'},
    // { username : 'ufruu2305', master: 'ufruu23'},
    // { username : 'ufruu2a02', master: 'ufruu2a'},
    // { username : 'ufruu2a04', master: 'ufruu2a'},
    // { username : 'ufruu2b01', master: 'ufruu2b'},
    // { username : 'ufruu2c01', master: 'ufruu2c'},
    // { username : 'ufruu2d04', master: 'ufruu2d'},
    // { username : 'ufruu9918', master: 'ufruu99'},
    // { username : 'ufruv0301', master: 'ufruv03'},
    // { username : 'ufruu1f07', master: 'ufruu1f'},
    // { username : 'ufruu0p39', master: 'ufruu0p'},
    // { username : 'ufruu0p38', master: 'ufruu0p'},
    // { username : 'ufruu0p37', master: 'ufruu0p'},
    // { username : 'ufruu0c12', master: 'ufruu0c'},
    // { username : 'ufruu0g15', master: 'ufruu0g'},
    // { username : 'ufruu0g17', master: 'ufruu0g'},
    // { username : 'ufruu0g18', master: 'ufruu0g'},
    // { username : 'ufruu0i25', master: 'ufruu0i'},
    // { username : 'ufruu0i31', master: 'ufruu0i'},
    // { username : 'ufruu0p40', master: 'ufruu0p'},
    // { username : 'ufruu0p42', master: 'ufruu0p'},
    // { username : 'ufruu0t08', master: 'ufruu0t'},
    // { username : 'ufruu0x24', master: 'ufruu0x'},
    // { username : 'ufruu16899', master: 'ufruu168'},
    // { username : 'ufruu1d23', master: 'ufruu1d'},
    // { username : 'ufruu1h05', master: 'ufruu1h'},
    // { username : 'ufruu2802', master: 'ufruu28'},
    // { username : 'ufruu2902', master: 'ufruu29'},
    // { username : 'ufruu2a01', master: 'ufruu2a'},
    // { username : 'ufruu6631', master: 'ufruu66'},
    // { username : 'ufruu6635', master: 'ufruu66'},
    // { username : 'ufruu6637', master: 'ufruu66'},
    // { username : 'ufruv0404', master: 'ufruv04'},
    // { username : 'ufruu0g14', master: 'ufruu0g'},
    // { username : 'ufruu0d09', master: 'ufruu0d'},
    // { username : 'ufruu0979', master: 'ufruu09'},
    // { username : 'ufruu0978', master: 'ufruu09'},
    // { username : 'ufruu0655', master: 'ufruu06'},
    // { username : 'ufruu0510', master: 'ufruu05'},
    // { username : 'ufruv0103', master: 'ufruv01'},
    // { username : 'ufruv0108', master: 'ufruv01'},
    // { username : 'ufruv0204', master: 'ufruv02'},
    // { username : 'ufruv0401', master: 'ufruv04'},
    // { username : 'ufruv0402', master: 'ufruv04'},
    // { username : 'ufruu0654', master: 'ufruu06'},
    // { username : 'ufruu0973', master: 'ufruu09'},
    // { username : 'ufruu0974', master: 'ufruu09'},
    // { username : 'ufruu0975', master: 'ufruu09'},
    // { username : 'ufruu0d08', master: 'ufruu0d'},
    // { username : 'ufruu0g13', master: 'ufruu0g'},
    // { username : 'ufruu0i29', master: 'ufruu0i'},
    // { username : 'ufruu0i30', master: 'ufruu0i'},
    // { username : 'ufruu0p35', master: 'ufruu0p'},
    // { username : 'ufruu1506', master: 'ufruu15'},
    // { username : 'ufruu1f08', master: 'ufruu1f'},
    // { username : 'ufruu1f09', master: 'ufruu1f'},
    // { username : 'ufruu1h04', master: 'ufruu1h'},
    // { username : 'ufruu1k02', master: 'ufruu1k'},
    // { username : 'ufruu1l02', master: 'ufruu1l'},
    // { username : 'ufruu1y11', master: 'ufruu1y'},
    // { username : 'ufruu2601', master: 'ufruu26'},
    // { username : 'ufruu2602', master: 'ufruu26'},
    // { username : 'ufruu0507', master: 'ufruu05'},
    // { username : 'ufruu0508', master: 'ufruu05'},
    // { username : 'ufruu0969', master: 'ufruu09'},
    // { username : 'ufruu0i26', master: 'ufruu0i'},
    // { username : 'ufruu0i27', master: 'ufruu0i'},
    // { username : 'ufruu0m29', master: 'ufruu0m'},
    // { username : 'ufruu0n12', master: 'ufruu0n'},
    // { username : 'ufruu0p30', master: 'ufruu0p'},
    // { username : 'ufruu1f06', master: 'ufruu1f'},
    // { username : 'ufruu1k01', master: 'ufruu1k'},
    // { username : 'ufruu1l01', master: 'ufruu1l'},
    // { username : 'ufruu2202', master: 'ufruu22'},
    // { username : 'ufruu6625', master: 'ufruu66'},
    // { username : 'ufruu6626', master: 'ufruu66'},
    // { username : 'ufruu0650', master: 'ufruu06'},
    // { username : 'ufruu0966', master: 'ufruu09'},
    // { username : 'ufruu0g11', master: 'ufruu0g'},
    // { username : 'ufruu0p15', master: 'ufruu0p'},
    // { username : 'ufruu1j01', master: 'ufruu1j'},
    // { username : 'ufruu1y09', master: 'ufruu1y'},
    // { username : 'ufruu0956', master: 'ufruu09'},
    // { username : 'ufruu0957', master: 'ufruu09'},
    // { username : 'ufruu0961', master: 'ufruu09'},
    // { username : 'ufruu0d07', master: 'ufruu0d'},
    // { username : 'ufruu0g07', master: 'ufruu0g'},
    // { username : 'ufruu0g10', master: 'ufruu0g'},
    // { username : 'ufruu1508', master: 'ufruu15'},
    // { username : 'ufruu1509', master: 'ufruu15'},
    // { username : 'ufruu1a03', master: 'ufruu1a'},
    // { username : 'ufruu1c05', master: 'ufruu1c'},
    // { username : 'ufruu1m08', master: 'ufruu1m'},
    // { username : 'ufruu1v01', master: 'ufruu1v'},
    // { username : 'ufruu1y08', master: 'ufruu1y'},
    // { username : 'ufruv0106', master: 'ufruv01'},
    // { username : 'ufruv0107', master: 'ufruv01'},
    // { username : 'ufruv0202', master: 'ufruv02'},
    // { username : 'ufruv0203', master: 'ufruv02'},
    // { username : 'ufruu091o', master: 'ufruu09'},
    // { username : 'ufruu0954', master: 'ufruu09'},
    // { username : 'ufruu0i18', master: 'ufruu0i'},
    // { username : 'ufruu0m27', master: 'ufruu0m'},
    // { username : 'ufruu0r03', master: 'ufruu0r'},
    // { username : 'ufruu0t05', master: 'ufruu0t'},
    // { username : 'ufruu0x0e', master: 'ufruu0x'},
    // { username : 'ufruu1808', master: 'ufruu18'},
    // { username : 'ufruu1810', master: 'ufruu18'},
    // { username : 'ufruu1d1c', master: 'ufruu1d'},
    // { username : 'ufruu1m0a', master: 'ufruu1m'},
    // { username : 'ufruu1t05', master: 'ufruu1t'},
    // { username : 'ufruu1y01', master: 'ufruu1y'},
    // { username : 'ufruu2006', master: 'ufruu20'},
    // { username : 'ufruu2201', master: 'ufruu22'},
    // { username : 'ufruu0645', master: 'ufruu06'},
    // { username : 'ufruu0948', master: 'ufruu09'},
    // { username : 'ufruu0j08', master: 'ufruu0j'},
    // { username : 'ufruu0m18', master: 'ufruu0m'},
    // { username : 'ufruu0m19', master: 'ufruu0m'},
    // { username : 'ufruu0m25', master: 'ufruu0m'},
    // { username : 'ufruu0p24', master: 'ufruu0p'},
    // { username : 'ufruu0p25', master: 'ufruu0p'},
    // { username : 'ufruu1608', master: 'ufruu16'},
    // { username : 'ufruu1805', master: 'ufruu18'},
    // { username : 'ufruu1806', master: 'ufruu18'},
    // { username : 'ufruu1807', master: 'ufruu18'},
    // { username : 'ufruu1809', master: 'ufruu18'},
    // { username : 'ufruu1907', master: 'ufruu19'},
    // { username : 'ufruu1d09', master: 'ufruu1d'},
    // { username : 'ufruu1d10', master: 'ufruu1d'},
    // { username : 'ufruu1d11', master: 'ufruu1d'},
    // { username : 'ufruu1d14', master: 'ufruu1d'},
    // { username : 'ufruu1d16', master: 'ufruu1d'},
    // { username : 'ufruu1f03', master: 'ufruu1f'},
    // { username : 'ufruu1t04', master: 'ufruu1t'},
    // { username : 'ufruu0640', master: 'ufruu06'},
    // { username : 'ufruu0943', master: 'ufruu09'},
    // { username : 'ufruu0950', master: 'ufruu09'},
    // { username : 'ufruu0g02', master: 'ufruu0g'},
    // { username : 'ufruu0g03', master: 'ufruu0g'},
    // { username : 'ufruu0g04', master: 'ufruu0g'},
    // { username : 'ufruu0i21', master: 'ufruu0i'},
    // { username : 'ufruu0i22', master: 'ufruu0i'},
    // { username : 'ufruu0m11', master: 'ufruu0m'},
    // { username : 'ufruu0m20', master: 'ufruu0m'},
    // { username : 'ufruu0n10', master: 'ufruu0n'},
    // { username : 'ufruu1607', master: 'ufruu16'},
    // { username : 'ufruu1804', master: 'ufruu18'},
    // { username : 'ufruu1c04', master: 'ufruu1c'},
    // { username : 'ufruu1e03', master: 'ufruu1e'},
    // { username : 'ufruu1f02', master: 'ufruu1f'},
    // { username : 'ufruu1t01', master: 'ufruu1t'},
    // { username : 'ufruu1t02', master: 'ufruu1t'},
    // { username : 'ufruu1t03', master: 'ufruu1t'},
    // { username : 'ufruu2003', master: 'ufruu20'},
    // { username : 'ufruu6620', master: 'ufruu66'},
    // { username : 'ufruv0102', master: 'ufruv01'},
    // { username : 'ufruv0105', master: 'ufruv01'},
    // { username : 'ufruu0505', master: 'ufruu05'},
    // { username : 'ufruu0951', master: 'ufruu09'},
    // { username : 'ufruu0a08', master: 'ufruu0a'},
    // { username : 'ufruu0p28', master: 'ufruu0p'},
    // { username : 'ufruu0x0f', master: 'ufruu0x'},
    // { username : 'ufruu1610', master: 'ufruu16'},
    // { username : 'ufruu1908', master: 'ufruu19'},
    // { username : 'ufruu1d20', master: 'ufruu1d'},
    // { username : 'ufruu1f05', master: 'ufruu1f'},
    // { username : 'ufruu1u02', master: 'ufruu1u'},
    // { username : 'ufruu1y05', master: 'ufruu1y'},
    // { username : 'ufruu0632', master: 'ufruu06'},
    // { username : 'ufruu0633', master: 'ufruu06'},
    // { username : 'ufruu0636', master: 'ufruu06'},
    // { username : 'ufruu0936', master: 'ufruu09'},
    // { username : 'ufruu0d03', master: 'ufruu0d'},
    // { username : 'ufruu0d04', master: 'ufruu0d'},
    // { username : 'ufruu0i17', master: 'ufruu0i'},
    // { username : 'ufruu0n04', master: 'ufruu0n'},
    // { username : 'ufruu0p11', master: 'ufruu0p'},
    // { username : 'ufruu0p20', master: 'ufruu0p'},
    // { username : 'ufruu0q02', master: 'ufruu0q'},
    // { username : 'ufruu0x15', master: 'ufruu0x'},
    // { username : 'ufruu0x17', master: 'ufruu0x'},
    // { username : 'ufruu1605', master: 'ufruu16'},
    // { username : 'ufruu1m06', master: 'ufruu1m'},
    // { username : 'ufruu0935', master: 'ufruu09'},
    // { username : 'ufruu0938', master: 'ufruu09'},
    // { username : 'ufruu0i15', master: 'ufruu0i'},
    // { username : 'ufruu0n05', master: 'ufruu0n'},
    // { username : 'ufruu1503', master: 'ufruu15'},
    // { username : 'ufruu1602', master: 'ufruu16'},
    // { username : 'ufruu1604', master: 'ufruu16'},
    // { username : 'ufruu0x12', master: 'ufruu0x'},
    // { username : 'ufruu9911', master: 'ufruu99'},
    // { username : 'ufruu0627', master: 'ufruu06'},
    // { username : 'ufruu0628', master: 'ufruu06'},
    // { username : 'ufruu0p09', master: 'ufruu0p'},
    // { username : 'ufruu0625', master: 'ufruu06'},
    // { username : 'ufruu0626', master: 'ufruu06'},
    // { username : 'ufruu0931', master: 'ufruu09'},
    // { username : 'ufruu0932', master: 'ufruu09'},
    // { username : 'ufruu0933', master: 'ufruu09'},
    // { username : 'ufruu0i13', master: 'ufruu0i'},
    // { username : 'ufruu0p08', master: 'ufruu0p'},
    // { username : 'ufruu0x11', master: 'ufruu0x'},
    // { username : 'ufruu1301', master: 'ufruu13'},
    // { username : 'ufruu6611', master: 'ufruu66'},
    // { username : 'ufruu990d', master: 'ufruu99'},
    // { username : 'ufruu990f', master: 'ufruu99'},
    // { username : 'ufruu9910', master: 'ufruu99'},
    // { username : 'ufruu0201', master: 'ufruu02'},
    // { username : 'ufruu021', master: 'ufruu02'},
    // { username : 'ufruu022', master: 'ufruu02'},
    // { username : 'ufruu023', master: 'ufruu02'},
    // { username : 'ufruu024', master: 'ufruu02'},
    // { username : 'ufruu025', master: 'ufruu02'},
    // { username : 'ufruu0301', master: 'ufruu03'},
    // { username : 'ufruu0302', master: 'ufruu03'},
    // { username : 'ufruu031', master: 'ufruu03'},
    // { username : 'ufruu0310', master: 'ufruu03'},
    // { username : 'ufruu032', master: 'ufruu03'},
    // { username : 'ufruu033', master: 'ufruu03'},
    // { username : 'ufruu034', master: 'ufruu03'},
    // { username : 'ufruu036', master: 'ufruu03'},
    // { username : 'ufruu037', master: 'ufruu03'},
    // { username : 'ufruu038', master: 'ufruu03'},
    // { username : 'ufruu039', master: 'ufruu03'},
    // { username : 'ufruu0400', master: 'ufruu04'},
    // { username : 'ufruu0401', master: 'ufruu04'},
    // { username : 'ufruu0402', master: 'ufruu04'},
    // { username : 'ufruu0403', master: 'ufruu04'},
    // { username : 'ufruu0404', master: 'ufruu04'},
    // { username : 'ufruu0406', master: 'ufruu04'},
    // { username : 'ufruu0408', master: 'ufruu04'},
    // { username : 'ufruu0409', master: 'ufruu04'},
    // { username : 'ufruu040a', master: 'ufruu04'},
    // { username : 'ufruu040b', master: 'ufruu04'},
    // { username : 'ufruu040c', master: 'ufruu04'},
    // { username : 'ufruu040d', master: 'ufruu04'},
    // { username : 'ufruu040e', master: 'ufruu04'},
    // { username : 'ufruu040f', master: 'ufruu04'},
    // { username : 'ufruu040g', master: 'ufruu04'},
    // { username : 'ufruu040h', master: 'ufruu04'},
    // { username : 'ufruu040i', master: 'ufruu04'},
    // { username : 'ufruu040k', master: 'ufruu04'},
    // { username : 'ufruu040l', master: 'ufruu04'},
    // { username : 'ufruu040m', master: 'ufruu04'},
    // { username : 'ufruu040n', master: 'ufruu04'},
    // { username : 'ufruu041', master: 'ufruu04'},
    // { username : 'ufruu042', master: 'ufruu04'},
    // { username : 'ufruu043', master: 'ufruu04'},
    // { username : 'ufruu044', master: 'ufruu04'},
    // { username : 'ufruu045', master: 'ufruu04'},
    // { username : 'ufruu046', master: 'ufruu04'},
    // { username : 'ufruu048', master: 'ufruu04'},
    // { username : 'ufruu049', master: 'ufruu04'},
    // { username : 'ufruu0500', master: 'ufruu05'},
    // { username : 'ufruu060', master: 'ufruu06'},
    // { username : 'ufruu0600', master: 'ufruu06'},
    // { username : 'ufruu0602', master: 'ufruu06'},
    // { username : 'ufruu0604', master: 'ufruu06'},
    // { username : 'ufruu0605', master: 'ufruu06'},
    // { username : 'ufruu0606', master: 'ufruu06'},
    // { username : 'ufruu0609', master: 'ufruu06'},
    // { username : 'ufruu060a', master: 'ufruu06'},
    // { username : 'ufruu060b', master: 'ufruu06'},
    // { username : 'ufruu060c', master: 'ufruu06'},
    // { username : 'ufruu060d', master: 'ufruu06'},
    // { username : 'ufruu060e', master: 'ufruu06'},
    // { username : 'ufruu060f', master: 'ufruu06'},
    // { username : 'ufruu060g', master: 'ufruu06'},
    // { username : 'ufruu060i', master: 'ufruu06'},
    // { username : 'ufruu060j', master: 'ufruu06'},
    // { username : 'ufruu060k', master: 'ufruu06'},
    // { username : 'ufruu060m', master: 'ufruu06'},
    // { username : 'ufruu060n', master: 'ufruu06'},
    // { username : 'ufruu060o', master: 'ufruu06'},
    // { username : 'ufruu060p', master: 'ufruu06'},
    // { username : 'ufruu060q', master: 'ufruu06'},
    // { username : 'ufruu060r', master: 'ufruu06'},
    // { username : 'ufruu060s', master: 'ufruu06'},
    // { username : 'ufruu060t', master: 'ufruu06'},
    // { username : 'ufruu060u', master: 'ufruu06'},
    // { username : 'ufruu060w', master: 'ufruu06'},
    // { username : 'ufruu060x', master: 'ufruu06'},
    // { username : 'ufruu060y', master: 'ufruu06'},
    // { username : 'ufruu060z', master: 'ufruu06'},
    // { username : 'ufruu0610', master: 'ufruu06'},
    // { username : 'ufruu0611', master: 'ufruu06'},
    // { username : 'ufruu0614', master: 'ufruu06'},
    // { username : 'ufruu0616', master: 'ufruu06'},
    // { username : 'ufruu0618', master: 'ufruu06'},
    // { username : 'ufruu0619', master: 'ufruu06'},
    // { username : 'ufruu0623', master: 'ufruu06'},
    // { username : 'ufruu0624', master: 'ufruu06'},
    // { username : 'ufruu065', master: 'ufruu06'},
    // { username : 'ufruu069', master: 'ufruu06'},
    // { username : 'ufruu0700', master: 'ufruu07'},
    // { username : 'ufruu0800', master: 'ufruu08'},
    // { username : 'ufruu0900', master: 'ufruu09'},
    // { username : 'ufruu0901', master: 'ufruu09'},
    // { username : 'ufruu0903', master: 'ufruu09'},
    // { username : 'ufruu0905', master: 'ufruu09'},
    // { username : 'ufruu0906', master: 'ufruu09'},
    // { username : 'ufruu0907', master: 'ufruu09'},
    // { username : 'ufruu0908', master: 'ufruu09'},
    // { username : 'ufruu090a', master: 'ufruu09'},
    // { username : 'ufruu090c', master: 'ufruu09'},
    // { username : 'ufruu090d', master: 'ufruu09'},
    // { username : 'ufruu090e', master: 'ufruu09'},
    // { username : 'ufruu090f', master: 'ufruu09'},
    // { username : 'ufruu090i', master: 'ufruu09'},
    // { username : 'ufruu090k', master: 'ufruu09'},
    // { username : 'ufruu090l', master: 'ufruu09'},
    // { username : 'ufruu090m', master: 'ufruu09'},
    // { username : 'ufruu090n', master: 'ufruu09'},
    // { username : 'ufruu090o', master: 'ufruu09'},
    // { username : 'ufruu090p', master: 'ufruu09'},
    // { username : 'ufruu090q', master: 'ufruu09'},
    // { username : 'ufruu090s', master: 'ufruu09'},
    // { username : 'ufruu090t', master: 'ufruu09'},
    // { username : 'ufruu090u', master: 'ufruu09'},
    // { username : 'ufruu090v', master: 'ufruu09'},
    // { username : 'ufruu090w', master: 'ufruu09'},
    // { username : 'ufruu090y', master: 'ufruu09'},
    // { username : 'ufruu090z', master: 'ufruu09'},
    // { username : 'ufruu0911', master: 'ufruu09'},
    // { username : 'ufruu0912', master: 'ufruu09'},
    // { username : 'ufruu0913', master: 'ufruu09'},
    // { username : 'ufruu0914', master: 'ufruu09'},
    // { username : 'ufruu0915', master: 'ufruu09'},
    // { username : 'ufruu0916', master: 'ufruu09'},
    // { username : 'ufruu0917', master: 'ufruu09'},
    // { username : 'ufruu0918', master: 'ufruu09'},
    // { username : 'ufruu0919', master: 'ufruu09'},
    // { username : 'ufruu091a', master: 'ufruu09'},
    // { username : 'ufruu091b', master: 'ufruu09'},
    // { username : 'ufruu091c', master: 'ufruu09'},
    // { username : 'ufruu091d', master: 'ufruu09'},
    // { username : 'ufruu091e', master: 'ufruu09'},
    // { username : 'ufruu091f', master: 'ufruu09'},
    // { username : 'ufruu091g', master: 'ufruu09'},
    // { username : 'ufruu091j', master: 'ufruu09'},
    // { username : 'ufruu091k', master: 'ufruu09'},
    // { username : 'ufruu091n', master: 'ufruu09'},
    // { username : 'ufruu0920', master: 'ufruu09'},
    // { username : 'ufruu0921', master: 'ufruu09'},
    // { username : 'ufruu0922', master: 'ufruu09'},
    // { username : 'ufruu0924', master: 'ufruu09'},
    // { username : 'ufruu0925', master: 'ufruu09'},
    // { username : 'ufruu0929', master: 'ufruu09'},
    // { username : 'ufruu0a01', master: 'ufruu0a'},
    // { username : 'ufruu0a02', master: 'ufruu0a'},
    // { username : 'ufruu0a03', master: 'ufruu0a'},
    // { username : 'ufruu0a04', master: 'ufruu0a'},
    // { username : 'ufruu0a05', master: 'ufruu0a'},
    // { username : 'ufruu0a06', master: 'ufruu0a'},
    // { username : 'ufruu0c04', master: 'ufruu0c'},
    // { username : 'ufruu0c05', master: 'ufruu0c'},
    // { username : 'ufruu0c07', master: 'ufruu0c'},
    // { username : 'ufruu0d01', master: 'ufruu0d'},
    // { username : 'ufruu0g00', master: 'ufruu0g'},
    // { username : 'ufruu0g01', master: 'ufruu0g'},
    // { username : 'ufruu0h01', master: 'ufruu0h'},
    // { username : 'ufruu0h03', master: 'ufruu0h'},
    // { username : 'ufruu0i00', master: 'ufruu0i'},
    // { username : 'ufruu0i04', master: 'ufruu0i'},
    // { username : 'ufruu0i05', master: 'ufruu0i'},
    // { username : 'ufruu0i07', master: 'ufruu0i'},
    // { username : 'ufruu0i08', master: 'ufruu0i'},
    // { username : 'ufruu0i09', master: 'ufruu0i'},
    // { username : 'ufruu0i0d', master: 'ufruu0i'},
    // { username : 'ufruu0i0e', master: 'ufruu0i'},
    // { username : 'ufruu0i0g', master: 'ufruu0i'},
    // { username : 'ufruu0i10', master: 'ufruu0i'},
    // { username : 'ufruu0j03', master: 'ufruu0j'},
    // { username : 'ufruu0j05', master: 'ufruu0j'},
    // { username : 'ufruu0j07', master: 'ufruu0j'},
    // { username : 'ufruu0k00', master: 'ufruu0k'},
    // { username : 'ufruu0k01', master: 'ufruu0k'},
    // { username : 'ufruu0l00', master: 'ufruu0l'},
    // { username : 'ufruu0l01', master: 'ufruu0l'},
    // { username : 'ufruu0m01', master: 'ufruu0m'},
    // { username : 'ufruu0m02', master: 'ufruu0m'},
    // { username : 'ufruu0m04', master: 'ufruu0m'},
    // { username : 'ufruu0m05', master: 'ufruu0m'},
    // { username : 'ufruu0n00', master: 'ufruu0n'},
    // { username : 'ufruu0p00', master: 'ufruu0p'},
    // { username : 'ufruu0p01', master: 'ufruu0p'},
    // { username : 'ufruu0p03', master: 'ufruu0p'},
    // { username : 'ufruu0p05', master: 'ufruu0p'},
    // { username : 'ufruu0p06', master: 'ufruu0p'},
    // { username : 'ufruu0r01', master: 'ufruu0r'},
    // { username : 'ufruu0t00', master: 'ufruu0t'},
    // { username : 'ufruu0t02', master: 'ufruu0t'},
    // { username : 'ufruu0t03', master: 'ufruu0t'},
    // { username : 'ufruu0u01', master: 'ufruu0u'},
    // { username : 'ufruu0u02', master: 'ufruu0u'},
    // { username : 'ufruu0u03', master: 'ufruu0u'},
    // { username : 'ufruu0v00', master: 'ufruu0v'},
    // { username : 'ufruu0x04', master: 'ufruu0x'},
    // { username : 'ufruu0x07', master: 'ufruu0x'},
    // { username : 'ufruu0x08', master: 'ufruu0x'},
    // { username : 'ufruu0x0b', master: 'ufruu0x'},
    // { username : 'ufruu0x10', master: 'ufruu0x'},
    { username : 'ufruu0y00', master: 'ufruu0y'},
    { username : 'ufruu0z00', master: 'ufruu0z'},
    { username : 'ufruu1300', master: 'ufruu13'},
    { username : 'ufruu1401', master: 'ufruu14'},
    { username : 'ufruu1700', master: 'ufruu17'},
    { username : 'ufruu1m02', master: 'ufruu1m'},
    { username : 'ufruu1m03', master: 'ufruu1m'},
    { username : 'ufruu6604', master: 'ufruu66'},
    { username : 'ufruu6605', master: 'ufruu66'},
    { username : 'ufruu6607', master: 'ufruu66'},
    { username : 'ufruu6609', master: 'ufruu66'},
    { username : 'ufruu9903', master: 'ufruu99'},
    { username : 'ufruu9904', master: 'ufruu99'},
    { username : 'ufruu9905', master: 'ufruu99'},
    { username : 'ufruu9906', master: 'ufruu99'},
    { username : 'ufruu990a', master: 'ufruu99'},
    { username : 'ufruu990b', master: 'ufruu99'},
    { username : 'ufruu0x56', master: 'ufruu0x'},
    { username : 'ufruu2z72', master: 'ufruu2z'},
    { username : 'ufruu3106', master: 'ufruu31'},
    { username : 'ufruu5534', master: 'ufruu55'},
    { username : 'ufruu6212', master: 'ufruu62'},
]
exports.UFRUU = [
    // { senior: 'ufruu', master: 'ufruu01', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu02', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu03', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu04', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu05', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu06', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu07', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu08', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu09', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu09', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu0a', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu0b', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu0c', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu0d', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu0g', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu0h', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu0i', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu0j', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu0k', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu0l', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu0m', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu0n', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu0p', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu0q', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu0r', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu0s', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu0t', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu0u', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu0v', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu0x', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu0y', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu0z', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu10', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu11', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu13', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu14', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu15', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu16', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu17', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu18', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu19', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu1a', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu1b', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu1c', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu1d', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu1e', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu1f', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu1g', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu1h', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu1i', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu1j', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu1k', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu1l', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu1m', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu1n', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu1o', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu1t', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu1u', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu1v', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu1w', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu1y', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu20', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu21', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu22', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu23', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu24', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu26', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu27', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu28', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu29', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2a', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2b', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2c', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2d', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2e', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2f', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2g', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2h', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2i', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2j', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2k', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2l', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2m', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2n', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2o', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2p', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2r', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2s', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2t', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2u', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2v', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2w', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2x', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2y', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu2z', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu30', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu31', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu32', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu33', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu34', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu35', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu36', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu37', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu38', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu39', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu3a', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu3b', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu3c', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu3d', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu3e', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu3f', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu3g', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu3h', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu40', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu41', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu42', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu43', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu44', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu47', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu48', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu49', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu50', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu51', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu52', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu53', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu54', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu55', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu56', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu58', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu61', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu62', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu64', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu65', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu66', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu68', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu71', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu88', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu99', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu9f', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'ufruu', master: 'ufruu9j', web: 'PSD99', userCheck: 'ufruuestvip' },
    // { senior: 'Ufruu', master: 'Ufruup1', web: 'PSD99', userCheck: 'Ufruuestvip' },
    // { senior: 'ufruv', master: 'ufruv01', web: 'PSD99', userCheck: 'ufruvestvip' },
    // { senior: 'ufruv', master: 'ufruv02', web: 'PSD99', userCheck: 'ufruvestvip' },
    // { senior: 'ufruv', master: 'ufruv03', web: 'PSD99', userCheck: 'ufruvestvip' },
    // { senior: 'ufruv', master: 'ufruv04', web: 'PSD99', userCheck: 'ufruvestvip' },
    // { senior: 'ufruv', master: 'ufruv05', web: 'PSD99', userCheck: 'ufruvestvip' },
]
