[
    [
        ' ',
        '',
        'User Name',
        'Nick Name',
        'Contact',
        'Currency',
        'Balance',
        'Credit Limit',
        'Downline',
        'Setting',
        'Login IP',
        'Last Login Date',
        'Create Date',
        'Password Lock',
        'Suspend',
        'Lock'
    ],
    [
        ' 1',
        '',
        'ufrcb18\tCopy',
        'ufrcb18',
        'Copy',
        '',
        'โอ๊ต',
        'THB',
        '-361,753',
        '380,000',
        'View',
        'Edit',
        '157.230.45.203',
        '05/10/2021 11:01 AM',
        '09/09/2020 06:33 PM',
        'OPEN',
        'NO',
        'OPEN'
    ],
    ['ufrcb18',
        'Copy'],
    [
        ' ',
        ' ',
        ' ',
        ' ',
        ' ',
        ' ',
        '-361,753',
        '380,000',
        ' ',
        ' ',
        ' ',
        ' ',
        ' ',
        ' ',
        ' ',
        ' '
    ]
]